### PR TITLE
Use Default Values in UsePagingAttribute (#4815)

### LINKED ISSUE #4815: Likely copy/paste error found in HotChocolate.Types.UsePagingAttribute
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Just familiarizing myself with the codebase and ran across what's likely a copy / paste error, given there are default values for the mis-mapped fields in HotChocolate.Types.Pagination.PagingDefaults.

``` csharp
    /// <summary>
    /// Allow backward paging using <c>last</c> and <c>before</c>
    /// </summary>
    public bool AllowBackwardPagination
    {
        get => _allowBackwardPagination ?? PagingDefaults.AllowBackwardPagination;
        set => _allowBackwardPagination = value;
    }

    /// <summary>
    /// Defines if the paging middleware shall require the
    /// API consumer to specify paging boundaries.
    /// </summary>
    public bool RequirePagingBoundaries
    {
        get => _requirePagingBoundaries ?? PagingDefaults.AllowBackwardPagination;
        set => _requirePagingBoundaries = value;
    }

    /// <summary>
    /// Connection names are by default inferred from the field name to
    /// which they are bound to as opposed to the node type name.
    /// </summary>
    public bool InferConnectionNameFromField
    {
        get => _inferConnectionNameFromField ?? PagingDefaults.AllowBackwardPagination;
        set => _inferConnectionNameFromField = value;
    }
```
The 2nd and 3rd properties listed above are all mapped to the default for `AllowBackwardPagination` if no override is supplied.

### Steps to reproduce

1. Visit https://github.com/ChilliCream/hotchocolate/blob/c479c10343f22328f708dc4d8e80f98a76bbf518/src/HotChocolate/Core/src/Types.CursorPagination/Extensions/UsePagingAttribute.cs

### Relevant log output

_No response_

### Additional Context?

_No response_

### Product

Hot Chocolate

### Version

12 (HEAD of repo)

### PR DESCRIPTION
**Pull request by treymack**
The production code changes are straightforward. If you have concerns / feedback on the test, please let me know.

Closes #4815

### CODE REVIEW

**Review by tobias-tengler — APPROVED** [review]
Thanks :)

**Comment by michaelstaib** [comment]
Looks good.

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
Thanks for contributing!

**Pull request merged**
