### PR TITLE
Add DbContext extension method to ResolverContext

### PR DESCRIPTION
**Pull request by tobias-tengler**
Allows to retrieve an instance of a `DbContext` from the `LocalContextData`:

```csharp
descriptor
    .Field("books")
    .UseDbContext<BookContext>()
    .Resolve(ctx =>
    {
        BookContext context = ctx.DbContext<BookContext>();

        return context.Books;
    });
```

Previously users would have to do something like:
```csharp
string contextKey = typeof(BookContext).FullName ?? typeof(BookContext).Name;
BookContext context = ctx.GetLocalValue<BookContext>(contextKey);
```

### CODE REVIEW

**Comment by tobias-tengler** [comment]
@michaelstaib is this something we want to support? I saw in an issue this morning that it's currently not possible to use the dbcontext integration like this.
I placed it in Data.EntityFramework for now, since initially I wanted to call it DbContext, but then I decided to name it ScopedService just like the attribute (which I'm not a fan of still).
Where would be a good place to put this? The attribute lives in abstractions, but it doesn't feel like this would belong there too...

**Comment by michaelstaib** [comment]
I was thinking in simplifying this even more ... still not sure on how to do that without impacting perf to much. 

We could under the hood really use `Service<>` and `[Service]` and do the lookup work. We actually should know which service is scoped. If there is at least one scoped service middleware in the pipeline we would go and take that service from the state.

So, essentially we would set a flag on the local context data... `scoped:true` if this is there we would first check if the requested service is available on the context data, otherwise we would take it from the service provider. This would also remove all the confusion around this.

what do you think?

**Comment by tobias-tengler** [comment]
> I was thinking on simplifying this even more ... still not sure on how to do that without impacting perf to much.
> 
> We could under the hood really use `Service<>` and `[Service]` and do the lookup work. We actually should know which service is scoped. If there is at least one scoped service middleware in the pipeline we would go and take that service from the state.
> 
> So, essentially we would set a flag on the local context data... `scoped:true` if this is there we would first check if the requested service is available on the context data, otherwise we would take it from the service provider. This would also remove all the confusion around this.
> 
> what do you think?

Hmm, re-using the Service functionality would actually make the problem worse in my opinion. Now you have the Service functionality to access Dependency Injection services. With your proposed change it would get a special case for something that's technically unrelated to Dependency Injection.

I've been thinking about maybe introducing these special cases, for the LocalState functionality, since they would kind of make sense there for me atleast.

If we for example have the LocalStateAttribute without a key:
```csharp
public string Test([LocalState] BooksContext context)
```
it would use the typename to do the lookup.

Same for Code-first:
```csharp
context.GetLocalValue<BooksContext>();
```

This should make it clearer to consumers where the DbContext is actually coming from.

What do you think?

**Comment by michaelstaib** [comment]
I think the issue for many people is that it is kind of DI and they just expect it to work like DI. Most people using field services do not reflect what we do underneath. That is why I think creating the illusion that its just DI will make this better. Since it does not matter to most how it works really. 

I guess lets revisit it when we have finished 12.

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
I am merging this one and we have a discussion on how to make the scoped service behavior better in the next release.

**Pull request merged**
