### PR TITLE
Added extension method to add custom validation rules.

### PR DESCRIPTION
**Pull request by cjstevenson**
Summary of the changes (Less than 80 chars)
Added the missing `this` keyword to make `RequestExecutorBuilderExtensions.ConfigureValidation` an extension method.

Addresses #2449

### CODE REVIEW

**Comment by PascalSenn** [comment]
@michaelstaib  i think this was a bug, in case it was intended like this we should make the `ConfigureValidation` private

**Comment by michaelstaib** [comment]
Let me have a look

**Comment by michaelstaib** [comment]
I reworked it to have a dedicated way to add custom validation rules. I will need to write some tests for this and then we will merge it.

**Review by michaelstaib — APPROVED** [review]

**Pull request merged**
