### PR TITLE
implemented concurrent processing for queries in an apollo style batch

### PR DESCRIPTION
**Pull request by martetassyns**
Concurrent batch query processing feature extracted from https://github.com/ChilliCream/hotchocolate/pull/3620.

Attached are results from Core benchmark including the still pending tests from https://github.com/ChilliCream/hotchocolate/pull/4660

[Core-Benchmark-Execution MaxConcurrentBatchQueries is 5.md](https://github.com/ChilliCream/hotchocolate/files/7896302/Core-Benchmark-Execution.MaxConcurrentBatchQueries.is.5.md)
[Core-Benchmark-Execution before changes.md](https://github.com/ChilliCream/hotchocolate/files/7896303/Core-Benchmark-Execution.before.changes.md)
[Core-Benchmark-Execution MaxConcurrentBatchQueries is 1.md](https://github.com/ChilliCream/hotchocolate/files/7896304/Core-Benchmark-Execution.MaxConcurrentBatchQueries.is.1.md)

### CODE REVIEW

**Comment by michaelstaib** [comment]
Is this ready for review?

**Comment by martetassyns** [comment]
It is now (only thing remaining was to make sure it passes all quality checks which it does now).

**Comment by michaelstaib** [comment]
@martetassyns I will give it a review tomorrow :)

**Comment by martetassyns** [comment]
@michaelstaib Hi, I noticed that this item was closed without integrating it into main. What was wrong/missing?

**Comment by martetassyns** [comment]
@michaelstaib Another poke, since no response yet after some months...

**Pull request closed without merging**
