### PR TITLE
🚧 Support endpoint routing in .NET Core 3.0

### LINKED ISSUE #1189: How to add authentication to GraphQL endpoint in .NET Core 3.0?
I've read the section about authorization on https://hotchocolate.io/docs/next/authorization, and it says one could opt in to the authentication provided by ASP.NET. 

My project already uses authentication based on JWT bearer tokens plugged into the authentication pipeline provided by ASP.NET, but I'm still not sure how I would go about adding authentication to the GraphQL endpoint.

What's new in .NET Core 3.0 is the configuration of endpoints, which also allows you to specify which endpoints require authentication. Below is how I'm configuring my app now:

```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseRouting();
    app.UseCors();

    app.UseAuthentication();
    app.UseAuthorization();

    app.UseWebSockets();
    
    app.UseGraphQL("/graphql");
    app.UsePlayground("/graphql");
    
    app.UseEndpoints(endpoints =>
    {
        endpoints
            .MapHub<NotificationHub>("/notifications")
            .RequireAuthorization();
        
        endpoints
            .MapControllers()
            .RequireAuthorization();
        
        endpoints.MapHealthChecks("/health");
    });
}
```

As you can see, I've configured the hub and controllers to require authentication. The current GraphQL middleware does not seem to use endpoints, and I also don't see an option where I could configure authentication for the middleware.

What does work is configuring a fallback policy in the ASP.NET authentication pipeline which requires an authenticated user. However, that is conflicting with the health endpoint, which needs to be unauthenticated since that's used by the Kubernetes cluster.

Any pointers on how to deal with this?

### PR DESCRIPTION
**Pull request by dmeenhuis**
This PR adds support for the new endpoint routing feature in .NET Core 3.0. Closes #1189 

I wasn't entirely sure about the reference to `Microsoft.AspNetCore.App`, but it seems libraries targeting .NET Core 3.0 that need stuff from ASP.NET now need a framework reference.

From what I could tell there is no such equivalent for .NET Core 2.2 or earlier, nor for classic.

### CODE REVIEW

**Comment by michaelstaib** [comment]
Thank you for your contribution. I will look into this now.

**Comment by michaelstaib** [comment]
It seems to have broken the stitching layer. I will have a look what the problem is.

**Comment by dmeenhuis** [comment]
I believe I have a fix for the broken tests, on my machine I'm able to run them again. Updating `Microsoft.AspNetCore.TestHost` to version `3.0.0` seems to do the trick.

**Comment by michaelstaib** [comment]
I will have a closer look tomorrow at this.

**Comment by michaelstaib** [comment]
Sorry for the wait on this one, did not have the time so far. But this one is on my mind so have a little patience please.

**Comment by michaelstaib** [comment]
I think we will retarget this and move it into 10.3.0

**Comment by michaelstaib** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1

**Comment by rstaib** [comment]
@michaelstaib Do we really want to offer .Net Core version specific features or do we want to offer features consistent through all supported .Net Core versions?

**Comment by michaelstaib** [comment]
@rstaib yes we do. The new routing brings a lot of benefits.

**Pull request merged**
