### PR TITLE
F# Support

### PR DESCRIPTION
**Pull request by michaelstaib**
This PR represents the initial work to determine what we need to make this a great API for F#.

In this initial PR we will re-create the StarWars example with F# and write some F# unit tests to see where the pain points are.

Todo:
- [ ] F# StarWars
- [ ] F# Integration Tests
- [ ] F# Union Support

https://github.com/adelarsq/hotchocolate_fsharp_sample

### CODE REVIEW

**Comment by sep2** [comment]
Is it possible to represent non-nullable GraphQL type by F# record? now I can do nullable type with:
```F#
[<ReferenceEquality>]
type Author = { Name: string }

[<ReferenceEquality>]
type Book = { Title: string; Author: Author }

type PortalQuery() =
    member this.Book() =
        { Title = "F#"
          Author = { Name = "Jon" } }

type PortalMutation() =
    member this.CreateBook() =
        { Title = "F#"
          Author = { Name = "Jon" } }

```

**Comment by sep2** [comment]
Never mind, I found this `[<GraphQLNonNullType>]` attribute is exactly what I want.

**Comment by Zaid-Ajaj** [comment]
Hi @michaelstaib F# support with HotChocolate would be awesome! I will be looking forward to testing it out with [Snowflaqe](https://github.com/Zaid-Ajaj/Snowflaqe) 🙏

**Comment by geekox86** [comment]
Hello @michaelstaib. Are we expecting this in Sept. milestone? What would it include in terms of F# support?

**Comment by Ciantic** [comment]
This is a bit cumbersome in F#:

```F#
type Query() =
    member this.Book() =
        { Title = "F#"
          Author = { Name = "Jon" } }

type Mutation() =
    member this.CreateBook() =
        { Title = "F#"
          Author = { Name = "Jon" } }
```

There is no partial classes, it gets awkward. Secondly these classes feel redundant, especially in F#. Mutation functions usually are not dependent on each other by state, so they shouldn't share class anyway.

I'd prefer in F# if we could define mutations and queries like functions. If it's possible, by allowing somehow to annotate functions with "Mutation":

```F#
[<Mutation>]
let createBook book (appDbContext: AppDbContext) =
    appDbContext.Books.Add(book) |> ignore
    appDbContext.SaveChanges()
    // ... 
```

**Comment by michaelstaib** [comment]
@Ciantic are there global functions in F# or are they always members of a class or struct?

**Comment by michaelstaib** [comment]
OK, looked at it ... seems to work ... I can probably put something into one of the next builds ... I think with this kind of function it can also become quite nice to create schema first and define resolvers... have to play a bit with it

**Comment by Ciantic** [comment]
It's notable that in F# the functions are usually defined in curried form, which also requires support in the HotChocolate to work well. Like `input -> AppDbContext -> PersonPayload`  I also started my simple example repo here:

https://github.com/Ciantic/TestGraphQLWithFsharp/blob/master/Program.fs

**Comment by mika76** [comment]
I'm sure there's plenty of people who wouldn't want this closed?

**Comment by adelarsq** [comment]
I am interested on this too.

**Comment by mika76** [comment]
was this PR forgotten?

**Comment by michaelstaib** [comment]
I am closing this PR as we have a newer one #5595.

**Pull request closed without merging**
