### PR TITLE
Serialize directives types following the GraphQL spec

### LINKED ISSUE #855: Serialized directive definitions do not follow the GraphQL Specification
As part of #716 directive definitions are not included in the serialized schema. It looks like the format does not follow the [specification](https://graphql.github.io/graphql-spec/June2018/#sec-Type-System.Directives).

For example in a stitched schema the `@source` directive is used. It's current serialization looks like the following:
```
"Annotates the original name of a type."
directive @source("The original name of the annotated type." name: Name! "The name of the schema to which this type belongs to." schema: Name!) repeatable on Enum | Object | Interface | Union | InputObject | FieldDefinition | InputFieldDefinition | ArgumentDefinition | EnumValue
```

I would expect something like
```
"Annotates the original name of a type."
directive @source("The original name of the annotated type." name: Name! "The name of the schema to which this type belongs to." schema: Name!) on ENUM | OBJECT | INTERFACE | UNION | INPUT_OBJECT | FIELD_DEFINITION | INPUT_FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM_VALUE
```
The important differences besides the casing on the locations are:
1. The `repeatable` concept for directives is not part of the specification.
2. `FieldDefinition` vs `FIELD_DEFINITION`.

### PR DESCRIPTION
**Pull request by nigel-sampson**
- Use correct locations.

Fixes #855.

### CODE REVIEW

**Comment by michaelstaib** [comment]
Repeatable is in the 2019 spec that is coming out this year.

**Comment by michaelstaib** [comment]
https://github.com/graphql/graphql-spec/pull/472/files

**Comment by michaelstaib** [comment]
We implement features once they are draft status

**Comment by nigel-sampson** [comment]
PR rebuilt to keep `repeatable`,  Noted our problems with it in #855.

**Pull request merged**
