### PR TITLE
Switch date handling to None in stitching layer

### LINKED ISSUE #930: Default JsonSerializer settings causes type issues
In the stitching layer the default date handling is set to [`DateParseHandling.DateTimeOffset`](https://github.com/ChilliCream/hotchocolate/blob/master/src/Stitching/Stitching/Utilities/HttpQueryClient.cs#L21).

This causes issues where a field is of type `String` but contains a value that looks like a date. This causes the error below.

> The internal resolver value could not be converted to a valid value of `String`.

If feels like this setting is an opinionated one and the stitching layer should simply pass the date through.

### PR DESCRIPTION
**Pull request by nigel-sampson**
Having a default setting of `DateParseHandling.DateTimeOffset` causes errors on any field of type `String` where the value looks like a date.

Resolves #930

### CODE REVIEW

**Comment by michaelstaib** [comment]
I have swapped out the json.net parser and added our new request parser here....

**Comment by michaelstaib** [comment]
Our own json parser creates the data in the structure we need and only recognizes the base data types... so there is not sting analyzation for date times and stuff like that. Moreover, we are getting the json as dictionary structure which is better for the resolver pipeline.

**Comment by michaelstaib** [comment]
OH, this one now does fixes a lot of bugs in stitching .... I found that a lot of stitching errors were there because all literals were deserialized in a wrong way. I fixed that now ...

**Comment by nigel-sampson** [comment]
Awesome, what other class of bugs did this find, just so I can make teams here aware of them.

**Comment by michaelstaib** [comment]
1. There were lots of issues with DateTime where the TimeZone was not correctly deserialized
2. When there was a scalar field imported into a type then this scalar was not correctly deserialized which lead to some conversion issues.
3. Scalar Lists where not not correctly handled and would have caused errors.

I wonder if this also fixed the issue when we want to pass on a list of scalars. I will look at this tomorrow :)

We are now using the `Utf8GraphQLRequestParser` to deserialize Json. The request parser is a specialized parser that can parse GraphQL request, GraphQL subscription messages and Json into a generic dictionary structure that fits perfectly the needs of the stitching middleware.

The Json.Net Parser was not good for that and handled quite to many cases that we do not want to be handled like the DateTime, since the scalar types are supposed to handle these.

I will do another refinement to this change tomorrow, because I think there might still be two more cases where we could get conversion issues. Also I will have a look into the variable conversion issue that you posted. I do not yet know where this comes from.

These updates should make the stitching layer much more robust.

**Comment by nigel-sampson** [comment]
It looks like we're still using json.net for serializing requests?

**Pull request merged**
