### PR TITLE
Add schema interceptor delegates + extensions

### PR DESCRIPTION
**Pull request by sergeyshaykhullin**
## Problem
I am using `builder.OnBeforeCompleteType` for type interceptor, but for schema interceptor i should create my own type or create DelegateSchemaInterceptor manually

## Changes
I found that `SchemaInterceptor` has `DelegateSchemaInterceptor`, but only  `onError` has its own extension for `IRequestExecutorBuilder`

Added delegates: `OnBeforeSchemaCreate`, `OnAfterSchemaCreate`, `OnSchemaError`
Added extensions: `builder.OnBeforeSchemaCreate`, `builder.OnAfterSchemaCreate`

## Additional info
Changing `DelegateSchemaInterceptor` ctor parameter types is a possible **breaking change**

### CODE REVIEW

**Comment by michaelstaib** [comment]
Looks good ...

**Comment by michaelstaib** [comment]
The build issues will be gone once we merged strawberry shake ...

**Comment by sergeyshaykhullin** [comment]
@michaelstaib Do i need to do something? Or strawberry shake is not yet merged?

**Comment by michaelstaib** [comment]
@sergeyshaykhullin not really this is just waiting for someone of the team to resolve the merge conflicts :)

**Review by michaelstaib — APPROVED** [review]

**Pull request merged**
