### PR TITLE
Fix variable stitching v11 (Issue 1761)

### PR DESCRIPTION
**Pull request by joslat**
Summary of the changes 
Applying fix for Issue https://github.com/ChilliCream/hotchocolate/issues/1761
which is a copy of https://github.com/ChilliCream/hotchocolate/pull/1746
Basically went over all the files and applied the changes in V11.

Some tests do not run properly in my machine, so consider this a WIP.
I did not add the WIP to the PR as it would not run and we want it to run.

Addresses #1761 (in this specific format)

### CODE REVIEW

**Comment by michaelstaib** [comment]
I have merged the master in again ... when it goes green we will merge it.

**Comment by joslat** [comment]
So, that's it I guess. Thanks Pascal!

**Comment by michaelstaib** [comment]
needs another merge... rafi has commited into master ... but it will go through now.

**Comment by michaelstaib** [comment]
@joslat welcome as contributor :)

**Comment by joslat** [comment]
Thanks Michael & Pascal!

**Pull request merged**
