### PR TITLE
Improve robustness of Uuid deserilization

### LINKED ISSUE #3562: Guid serialization in strawberry shake only accepts one format.
StrawberryShake only seems to recognize uuid values in "D" form (aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee). Is there a way to get it to use "N" form (aaaaaaaabbbbccccddddeeeeeeeeeeee)?

### PR DESCRIPTION
**Pull request by dmg-hamann**
replace JsonElement GetGuid with GetString and add Guid.Parse to deserialize Uuids

Closes #3562

### CODE REVIEW

**Comment by michaelstaib** [comment]
Hi there,

thanks for contributing!

I was already thinking about making Guids in general more robust. I think if we change the ScalarSerializer and set the the default Guid serialization to string we will get a more robust behavior all over the client. In this case I would actually revert the change that you did an solve the issue at the root.

Do you think you can rework this?

The default mapping is defined here:
https://github.com/ChilliCream/hotchocolate/blob/4d07a66f4addc04d27461b842e62260ca6790342/src/StrawberryShake/CodeGeneration/src/CodeGeneration/Utilities/SchemaHelper.cs#L234

All uuid aliases need to have a default serialization type of string instead of Guid.

Once this is done we only need to rework the serializer:
https://github.com/ChilliCream/hotchocolate/blob/4d07a66f4addc04d27461b842e62260ca6790342/src/StrawberryShake/Client/src/Core/Serialization/UuidSerializer.cs#L8

At the moment the serializer just passes the value through, but now that we set the Guid default serialization to string we need to make it a proper serializer like Url:
https://github.com/ChilliCream/hotchocolate/blob/develop/src/StrawberryShake/Client/src/Core/Serialization/UrlSerializer.cs

Michael

**Review by michaelstaib — CHANGES_REQUESTED** [review]
Hi there,

thanks for contributing!

I was already thinking about making Guids in general more robust. I think if we change the ScalarSerializer and set the the default Guid serialization to string we will get a more robust behavior all over the client. In this case I would actually revert the change that you did an solve the issue at the root.

Do you think you can rework this?

The default mapping is defined here:
https://github.com/ChilliCream/hotchocolate/blob/4d07a66f4addc04d27461b842e62260ca6790342/src/StrawberryShake/CodeGeneration/src/CodeGeneration/Utilities/SchemaHelper.cs#L234

All uuid aliases need to have a default serialization type of string instead of Guid.

Once this is done we only need to rework the serializer:
https://github.com/ChilliCream/hotchocolate/blob/4d07a66f4addc04d27461b842e62260ca6790342/src/StrawberryShake/Client/src/Core/Serialization/UuidSerializer.cs#L8

At the moment the serializer just passes the value through, but now that we set the Guid default serialization to string we need to make it a proper serializer like Url:
https://github.com/ChilliCream/hotchocolate/blob/develop/src/StrawberryShake/Client/src/Core/Serialization/UrlSerializer.cs

Michael

**Comment by dmg-hamann** [comment]
@michaelstaib I will reimplement it the way you described it and create a new pull request :) Thanks for the feedback

Marco

**Comment by dmg-hamann** [comment]
I close this pr and create a new one from a new branch instead of reverting commits on current branch

**Pull request closed without merging**
