### PR TITLE
Fixes: Strawberry Shake Tooling download command does not send scope(s) to token endpoint.

### LINKED ISSUE #5319: Strawberry Shake Tooling download command does not send scope(s) to token endpoint
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Trying to use the download command  dotnet graphql download retrieving the token from azure ad to pass to our graphql endpoint in order to retrieve schema generates unhandled exception.

### Steps to reproduce

1. Attempt to run dotnet graphql download passing --tokenEndpoint --clientId --clientSecret and --scope

### Relevant log output

```shell
Unhandled exception. System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at HotChocolate.Utilities.Introspection.IntrospectionClient.ExecuteIntrospectionAsync(HttpClient client, HttpQueryRequest request, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/HotChocolate/Utilities/src/Utilities.Introspection/IntrospectionClient.cs:line 144
   at HotChocolate.Utilities.Introspection.IntrospectionClient.GetSchemaFeaturesAsync(HttpClient client, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/HotChocolate/Utilities/src/Utilities.Introspection/IntrospectionClient.cs:line 92
   at HotChocolate.Utilities.Introspection.IntrospectionClient.DownloadSchemaAsync(HttpClient client, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/HotChocolate/Utilities/src/Utilities.Introspection/IntrospectionClient.cs:line 67
   at HotChocolate.Utilities.Introspection.IntrospectionClient.DownloadSchemaAsync(HttpClient client, Stream stream, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/HotChocolate/Utilities/src/Utilities.Introspection/IntrospectionClient.cs:line 49
   at StrawberryShake.Tools.DefaultFileSystem.WriteToAsync(String fileName, Func`2 write) in /home/vsts/work/1/s/src/StrawberryShake/Tooling/src/dotnet-graphql/DefaultFileSystem.cs:line 81
   at StrawberryShake.Tools.IntrospectionHelper.DownloadSchemaAsync(HttpClient client, IFileSystem fileSystem, IActivity activity, String fileName, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/StrawberryShake/Tooling/src/dotnet-graphql/IntrospectionHelper.cs:line 21
   at StrawberryShake.Tools.DownloadCommandHandler.DownloadSchemaAsync(DownloadCommandContext context, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/StrawberryShake/Tooling/src/dotnet-graphql/DownloadCommandHandler.cs:line 64
   at StrawberryShake.Tools.DownloadCommandHandler.ExecuteAsync(DownloadCommandArguments arguments, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/StrawberryShake/Tooling/src/dotnet-graphql/DownloadCommandHandler.cs:line 49
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at StrawberryShake.Tools.Program.<Main>(String[] args)
```

### Additional Context?

Running tooling code in debug the problem appears to be in hotchocolate-12.12.1\src\StrawberryShake\Tooling\src\dotnet-graphql\OAuth\AuthArgumentsBase.cs

Lines 62,63,64 currently are:
```
                IEnumerable<string> scopes = Scopes.HasValue()
                    ? Enumerable.Empty<string>()
                    : Scopes.Values.Where(t => t is { }).OfType<string>();

```
This code returns the Enumerable.Empty when Scopes.HasValue() is true.

It should be:
```
                IEnumerable<string> scopes = Scopes.HasValue()
                    ? Scopes.Values.Where(t => t is { }).OfType<string>()
                    : Enumerable.Empty<string>();

```
returning a collection of scopes if there are any and an empty collection if not.

Happy to submit this as a PR with a little guidance.

### Product

Strawberry Shake

### Version

12.12.1

### PR DESCRIPTION
**Pull request by charristti**
- reversed the order of the ternary conditional operation so that when scopes are provided they are passed on to the call tothe oauth endpoint

Closes #5319

### CODE REVIEW

**Comment by michaelstaib** [comment]
@charristti thank you for your contribution. Could you sign the CLA so we can go forward with the PR?

https://cla-assistant.io/ChilliCream/hotchocolate?pullRequest=5340

**Comment by michaelstaib** [comment]
@charristti can you sign the CLA?

https://cla-assistant.io/ChilliCream/hotchocolate?pullRequest=5340

**Comment by charristti** [comment]
I think I finally got it to go through

**Comment by charristti** [comment]
charristti shows signed now. Can you tell me how to fix the “Chuck Harris” problem?

**Review by michaelstaib — APPROVED** [review]

**Pull request merged**
