### PR TITLE
Change follwing to following

### PR DESCRIPTION
**Pull request by naufil09**
Spelling update

### CODE REVIEW

**Comment by naufil09** [comment]
> Thanks again! :)
> Are you planning to scan for more spelling mistakes? If so I'd like you to reuse this PR in order to reduce the overall volume of PRs.

No no, I was just reading the document for the my use and i found two spelling mistake.

**Comment by tobias-tengler** [comment]
> > Thanks again! :)
> > Are you planning to scan for more spelling mistakes? If so I'd like you to reuse this PR in order to reduce the overall volume of PRs.
> 
> No no, I was just reading the document for the my use and i found two spelling mistake.
> 
> Ok then i will reuse. if there is anything.

Okay, I'll leave it open for the day.

**Review by michaelstaib — APPROVED** [review]

**Comment by naufil09** [comment]
> > > Thanks again! :)
> > > Are you planning to scan for more spelling mistakes? If so I'd like you to reuse this PR in order to reduce the overall volume of PRs.
> > 
> > 
> > No no, I was just reading the document for the my use and i found two spelling mistake.
> > Ok then i will reuse. if there is anything.
> 
> Okay, I'll leave it open for the day.

Hey, I don't see any update changes in document.

**Comment by tobias-tengler** [comment]
These changes were made against develop, they'll be live, once v12 is released.

**Comment by michaelstaib** [comment]
The develop branch can be looked at here:
https://develop.chillicream.com

**Pull request merged**
