### PR TITLE
Fix bug in SelectionSetNode.AddSelections() and update test snap

### PR DESCRIPTION
**Pull request by Avilad**
3 character bugfix 😮

### CODE REVIEW

**Comment by michaelstaib** [comment]
Can you add another test that ads a selection to a field that already has a selection?

**Comment by michaelstaib** [comment]
And thanks for your help

**Comment by Avilad** [comment]
> Can you add another test that ads a selection to a field that already has a selection?

Unless I am misunderstanding you, there is already an existing test for this, which was succeeding because the snapshot file contained output from the buggy method. That was fixed in this PR. But let me know if you meant a different test.

**Comment by michaelstaib** [comment]
I see ... misread the snapshot... you are right.

**Pull request merged**
