### PR TITLE
New Platform Readme.md

### PR DESCRIPTION
**Pull request by michaelstaib**

### CODE REVIEW

**Comment by michaelstaib** [comment]
@benmccallum sure we can. Just do a commit to this pr, you should be able to.

**Comment by benmccallum** [comment]
@michaelstaib , done. Have a look and feel free to tweak as necessary. 

Thought it'd be good to have a list of example projects that people can browse, but didn't have any front of mind except yours, so added that. Feel free to tweak it's label/description. I can see this being broken down into 10.x and 11.x sub headings at some stage, but for now this'll do.

**Comment by benmccallum** [comment]
Also wasn't sure where to put the page, as there's no /docs directory, so hopefully root is OK with you, else feel free to move ofc.

**Comment by rstaib** [comment]
@michaelstaib I have to update the platform graphic before we merge this PR.

**Comment by rstaib** [comment]
I close this one because in the meantime too much has been changed.

**Pull request closed without merging**
