### PR TITLE
Issue 2031 Resolved by removing a redundant line.

### PR DESCRIPTION
**Pull request by DaanAcohen**
A redundant line ("using HotChocolate;") has been removed. This line triggered the compiler warning.

Merging shall resolve this issue
https://github.com/ChilliCream/hotchocolate/issues/2031

### CODE REVIEW

**Comment by michaelstaib** [comment]
Why does this trigger a compiler warning? If we remove that you do not have the extension methods available on the schema builder.

**Comment by DaanAcohen** [comment]
@michaelstaib The reason for the warning is described by the warning message itself (so there is no need to ask me) which I documented (https://github.com/ChilliCream/hotchocolate/issues/2031): "The using directive for 'HotChocolate' appeared previously in this namespace".

The only thing I removed is a duplication of a using directive. This becomes clear from these lines where the first one and the lost one are the same: https://github.com/ChilliCream/hotchocolate/blob/master/templates/Server/content/Startup.cs#L1-L5

All the using directives remain available after my change so the extension methods remain available too. But there is no need for duplication of using directives. I removed the duplication which makes the code more clear and resolves the warning I referred too.  Feel free to reproduce it with the steps I provided in the issue. The warning really exist and really disappears after my change.

**Comment by michaelstaib** [comment]
I see, overlooked this one yesterday night. Did not see that the `using HotChocolate;` was declared twice. Good catch.

Thanks for your contribution.

**Comment by michaelstaib** [comment]
Welcome as a Hot Chocolate contributor 🎉

**Pull request merged**
