### PR TITLE
Add RSS feed to website

### PR DESCRIPTION
**Pull request by jorrit**
This change adds an RSS feed to the ChilliCream website, allowing me to follow your blog with minimal effort :)

The thing in this PR that is unsatisfactory to me is that I add `site.pathPrefix` to the item url manually. I am new to Gatsby and I hope there is a better way.

### CODE REVIEW

**Comment by rstaib** [comment]
@jorrit thank you for adding the RSS feed; it looks good so far. I will just quickly check whether it works locally on my machine and if yes merge it into our dev branch.

**Comment by rstaib** [comment]
@jorrit unfortunately it seems not to work locally. Have you tried accessing the RSS feed locally and did it work?

**Comment by jorrit** [comment]
I did the following:

1. Run `yarn run build`
2. Run `yarn run serve`
3. Use an RSS reader to load http://localhost:9000/rss.xml.
4. I get this:

image

**Comment by rstaib** [comment]
Hey @jorrit,
I have implemented news feeds with a different plugin. We're now supporting ATOM, JSON and RSS feed.

**Comment by jorrit** [comment]
Thanks!

**Pull request closed without merging**
