### PR TITLE
notify observer to complete async stream

### PR DESCRIPTION
**Pull request by CoreDX9**
notify observer to complete async stream.

- If convert `IObservable{T}` to `IAsyncEnumerable` and use `await foreach` to enumerate stream, but observers never call `OnCompleted`, the thread will be permanently blocked.

see also #5006 .

### CODE REVIEW

**Comment by PascalSenn** [comment]
Very cool, thanks for the contribution :) 

Can you add one test case in the integration tests to test this behaviour? 

You can add a test case to 
https://github.com/ChilliCream/hotchocolate/blob/main/src/StrawberryShake/CodeGeneration/test/CodeGeneration.CSharp.Tests/Integration/TestGeneration.cs
that will generate the client. 

And then just type out a test case like 
https://github.com/ChilliCream/hotchocolate/blob/main/src/StrawberryShake/CodeGeneration/test/CodeGeneration.CSharp.Tests/Integration/StarWarsGetFriendsTest.cs

**Comment by CoreDX9** [comment]
No problem, but I need some time.

**Comment by CoreDX9** [comment]
In addition, this pull request can only let the client detect the subscription that ends normally. If the socket is closed due to server crash or network error, the client cannot receive the message of completing the subscription, so this notification will not be triggered. If you want to complete the subscription in this case, you may need to modify the interface definition. Because my interim solution needs to access non-public members through reflection to trigger the notification of subscription completion.

**Review by michaelstaib — APPROVED** [review]
Looks good to me... thanks for your help!

**Comment by michaelstaib** [comment]
@PascalSenn I will patch this into 12.9 so let's keep it open for now... I will merge it on the weekend.

**Comment by michaelstaib** [comment]
OK ... we now have a green main ... so lets see if this build is green.

**Review by michaelstaib — APPROVED** [review]

**Pull request merged**
