### PR TITLE
Fixed namespace of AddInMemorySubscriptions

### PR DESCRIPTION
**Pull request by barticus**
As it differed from AddRedisSubscriptions

Summary of the changes
- Updated namespace of InMemoryPubSubServiceCollectionExtensions class

Builds and tests pass locally

### CODE REVIEW

**Comment by michaelstaib** [comment]
The namespace is deliberately hot chocolate. We are moving all extension methods to HotChocolate so that you basically need one using `using HotChocolate` to have all the extensions imported.

**Comment by barticus** [comment]
So the redis one is incorrect instead?

The Microsoft recommendation is to put all service registration extensions in Microsoft.Extensions.DependencyInjection namespace.
See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1

**Comment by michaelstaib** [comment]
@barticus yes

**Comment by michaelstaib** [comment]
@barticus I will read through that. @PascalSenn and I think that we should discuss this in the next standup. Feel free to join. We should find a rule that we can then apply to the whole project. Once we have decided you can do the change if you like.

https://github.com/ChilliCream/hotchocolate-wg/blob/master/agendas/2020-03-31.md

**Comment by michaelstaib** [comment]
> Each services.Add{SERVICE_NAME} extension method adds (and potentially configures) services. For example, services.AddMvc() adds the services Razor Pages and MVC require. We recommended that apps follow this convention. Place extension methods in the Microsoft.Extensions.DependencyInjection namespace to encapsulate groups of service registrations.

**Comment by michaelstaib** [comment]
@barticus we have discussed this now in our standup and want to abide to the Microsoft rule. So all the dependency injection extension methods shall be moved to Microsoft.Extensions.DependencyInjection.

**Comment by barticus** [comment]
Thanks @michaelstaib , I'll try to tackle this in the next few days.

**Comment by michaelstaib** [comment]
This one is targeting version 10 .... so i am closing this one as well since we do not want to make any breaking changes on 10.

**Pull request closed without merging**
