### PR TITLE
Mark each Resolver() method as obsolete

### PR DESCRIPTION
**Pull request by jorrit**
While converting a HotChocolate v10 project to v11 I noticed that some `Resolver()` methods were marked as obsolete and some weren't. This appears to be caused by the fact that the extension methods in ResolverObjectFieldDescriptorExtensions need to be marked individually in order to have effect.
I've added `[Obsolete]` to each method.

### CODE REVIEW

**Review by tobias-tengler — APPROVED** [review]

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
The compile issue was introduced by my merge from main to dev ... I fixed that now.

**Comment by michaelstaib** [comment]
The failing tests are flaky ... I think ... validating.

**Comment by michaelstaib** [comment]
Thank @jorrit for your contributions!

**Pull request merged**
