### PR TITLE
Fix memory leak bug caused by query dictionary variable params

### LINKED ISSUE #5382: Strawberry Shake Dictionary Type Parameters Memory Leak
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Related to #3513 

When invoking queries where one or more of the variable parameters is a dictionary, this causes every repeat execution of the query to add another operation result to the operation store after every completed ExecuteAsync request. This is caused by the fact that the call to GetOrAddStoredOperation in OperationStore performs a GetOrAdd on the ConcurrentDictionary<OperationRequest, IStoredOperation> _result, the .Equals equality comparison within the OperationRequest object that acts as the key and thus invoked by GetOrAdd, when comparing the content of variables will always return false with a dictionary variable because it treats it as an IEnumerable and ComparisonHelper.SequenceEqual only works for lists and not dictionaries so therefore returns false. The result is that every invocation adds another item to _results which will keep growing indefinitely, triggering a memory leak as well as higher and higher cpu usage (every time more items in _results needs to be compared to).

### Steps to reproduce

Steps to reproduce the behaviour:

1. Execute ExecuteAsync on a query which has a dictionary type variable parameter
2. After 2 or more completed executions of the above with identical parameters on that same query upon inspecting _operationExecutor -> _operationStore -> _results it will be observed that another result gets added after each time

### Relevant log output

_No response_

### Additional Context?

**Expected behaviour**
If one of the variables is a list type, the contents of that dictionary needs to iterated and compared so that the comparison when GetOrAdd is executed correctly recognises that is another call to the same query and therefore the existing result should updated, not another one added; i.e. Get is triggered not Add.

**Desktop (please complete the following information):**

- OS: Windows 10
- .net: 6.0/7.0

**Additional context**
Using 12.3.0 Strawberry Shake, but checking the code, latest remains affected by this bug.

### Product

Strawberry Shake

### Version

12.3.0

### PR DESCRIPTION
**Pull request by declan-bourke**
When invoking queries where one or more of the variable parameters is a dictionary, this causes every repeat execution of the query to add another operation result to the operation store after every completed ExecuteAsync request. This is caused by the fact that the call to GetOrAddStoredOperation in OperationStore performs a GetOrAdd on the ConcurrentDictionary<OperationRequest, IStoredOperation> _result, the .Equals equality comparison within the OperationRequest object that acts as the key and thus invoked by GetOrAdd, when comparing the content of variables will always return false with a dictionary variable because it treats it as an IEnumerable and ComparisonHelper.SequenceEqual only works for lists and not dictionaries so therefore returns false. The result is that every invocation adds another item to _results which will keep growing indefinitely, triggering a memory leak as well as higher and higher cpu usage (every time more items in _results needs to be compared to).

Co-Authored-By: davidbrazel2 <47366627+davidbrazel2@users.noreply.github.com>

Summary of the changes (Less than 80 chars)

- Adds a check for the contents of a dictionary variable

Closes #5382

### CODE REVIEW

**Comment by michaelstaib** [comment]
@declan-bourke can you sign the CLA please.

**Comment by michaelstaib** [comment]
I will review this tonight.

**Review by michaelstaib — APPROVED** [review]

**Comment by lweberprb** [comment]
Will this be backported to v12?

**Comment by michaelstaib** [comment]
We are not far off the V13 release. So, I think it's not worth it. But If you want to have a go at it you can create a PR for the `main-version-12` branch and  I can create a new version. Up for it?

**Pull request merged**
