### PR TITLE
Fix use of Get() and GetAsync() as default node resolvers

### PR DESCRIPTION
**Pull request by GraemeF**
This fixes the use of `Get()` and `GetAsync()` as implicit node resolvers.

There was no way to reach `IsPossibleNodeResolver` which is used to find those functions because `GetNodeResolverMethod` was always given a `resolverType` (it was given the type of the node itself in the case where no type was explicitly set). This PR just passes `null` to `GetNodeResolverMethod` as was presumably intended.

### CODE REVIEW

**Comment by michaelstaib** [comment]
We start merging server changes mid of the coming week...

**Comment by michaelstaib** [comment]
Thanks for the work btw :)

**Comment by GraemeF** [comment]
Same to you 😁

**Review by michaelstaib — DISMISSED** [review]
Sorry for the wait :)

**Comment by michaelstaib** [comment]
There seems to be a test wrong ... is not really related to your fix. I will check and then restart merging this one.

**Comment by GraemeF** [comment]
Woohoo! Thanks @michaelstaib! <3

**Pull request merged**
