### PR TITLE
Fix CustomOperationFilterInput example

### PR DESCRIPTION
**Pull request by rmcc13**
Fix CustomOperationFilterInput example

- Fix example by configuring the types for each operation

Addresses #3217

### CODE REVIEW

**Review by PascalSenn — APPROVED** [review]
Thanks for this contribution!

**Comment by PascalSenn** [comment]
@rmcc13  Sorry that this one is open for such a long time, i didnt realize this PR exists!! LGTM

**Comment by michaelstaib** [comment]
@PascalSenn we need to retarget to main

**Pull request merged**
