### PR TITLE
Client Core API

### LINKED ISSUE #775: Integrate Client Core
- Lift and shift the octokit GraphQL client core into this repository.
- Integrate HotChocolate.Language into the client
- Remove Json.NET and use the new Utf8RequestParser instead
- Integrate and rewrite tests

### PR DESCRIPTION
**Pull request by michaelstaib**
The new Hot Chocolate client API is based on the work GitHub has done with its OctoClient. We will start by refactoring the client core to use our parser and remove dependencies on GitHub itself.

resolves #775

### CODE REVIEW

**Comment by michaelstaib** [comment]
@PascalSenn @willwolfram18 just added you two to keep you in the loop on this one so you can add your ideas as we move this forward.

**Comment by michaelstaib** [comment]
I have added the core so far and will start removing GitHub specific code .....

**Comment by willwolfram18** [comment]
Something that would be good to add is the ability to provide HTTP headers for a request that is made. This could be done with a `Headers` (or `RequestHeaders`) property on the `IQueryRequest` or as its own parameter to an overloaded `Run` method. I know it's not an uncommon practice to include metadata in headers for an HTTP request (request Ids, access tokens, etc.), and while it would be possible to use the `DefaultRequestHeaders` property on the `HttpClient` for some items, some requests may require distinct values for each individual request such as a request Id. This would mean the `DefaultRequestHeaders` wouldn't work in that scenario.

The abstract `HttpHeaders` class implements `IEnumerable<KeyValuePair<string, IEnumerable<string>>>` so this would likely be the best type to expose.

**Comment by willwolfram18** [comment]
Speaking of headers, not just being able to include them in the request but being able to access them from the request might be nice. Not sure how well that fits into this though, especially since GraphQL itself doesn't describe a specific protocol.

**Comment by michaelstaib** [comment]
@willwolfram18 I think if we use IHttpClientFactory you are able to provide handler that can provide headers....

regarding reading response headers, this might be more difficult. Since we are mapping to an object model. The question is how do we store them or map them to that model. I mean with a handler you can also grab these, but how do we bring them together with the data?

**Comment by PascalSenn** [comment]
@michaelstaib  Would it make sense to have a response object?  Like the way Apollo does it. 
{
    data: The recevied data
    reponse: HttpResponse
    ... otherProps
}

**Comment by michaelstaib** [comment]
Let me have a look at how relay does it.

**Comment by michaelstaib** [comment]
OK, just talked to our guys.... relay does not do that.

I think we have to look at this a different way. For what do we want to have access to the raw message? What do we actually want to do with the response headers. Are those part of the content that we want to consume?

If so we should extend the local schema and do some schema stitching on the client.

**Comment by michaelstaib** [comment]
Just to explain why I am thinking like that ....

I think the resulting graph should be very clean and very close to the structure that I want to consume. There should be no need to pass on the message. 

I mean there are ways to intercept the message baked in the http client and we can also allow interception in the connection layer but passing it on feels not good. I think it is very important that the new API feels very clean.

**Comment by PascalSenn** [comment]
I was just thinking this would have lower potential for breaking changes. 
Once you need some kind of context around the data you will not be able to add it to the response object

**Comment by michaelstaib** [comment]
@PascalSenn but I also would bind it tightly to HTTP and this would kind of render the connection abstraction useless. I can follow your argument but I just think this would expose to much implementation details.

**Comment by OneCyrus** [comment]
i guess handling this in a HttpFactory would be the better way (when using http as transport protocol at all)

**Comment by michaelstaib** [comment]
That is what I think... having HttpFactory allows us to handle and http relevant stuff with handlers... the one thing we additionally need is a way to map data like response headers to the object model.....


I favor something like the relay local schema extension... what if we had also local schema extensions like we allow to extend the schema:

```graphql
extend type Foo {
   someLocalData: String
}
```

and then we allow users to write resolvers on top of these extensions. This would lead to a consistent object model on which we can do queries. The fact that some data is computed on the client side is oblivious to the user. It would be clean.

**Comment by michaelstaib** [comment]
OK, lets talk more about the API. After looking a lot at the GitHub API I think we can move faster by starting from scratch but preserve their idea.

So, what do you think about an approach like this. 

```csharp
IQuery<MyFoo> query =  Schema.Query.Select(q => 
    new MyFoo  {
        q.Foo,
        q.Bar.Select(b => {
              b.Baz
        }
    }).Compile();

var myResult = query.ExecuteAsync(connection);
```

If you guys have other ideas pleas post them.

**Comment by michaelstaib** [comment]
This is very close to what the oktoclient is.

**Comment by michaelstaib** [comment]
```csharp
IQuery<MyFoo> query =  Schema.Query.Select(q => 
    new MyFoo  {
        q.Foo,
        q.Bar.Select(b => new MyBar {
              b.Baz
        }
        q.Qux.OneOf(t => 
        {
             t.On<MyTypeA>....
             t.On<MyTypeB>....

        })
    }).Compile();

var myResult = query.ExecuteAsync(connection);
```

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/octokit.graphql.net

**Comment by michaelstaib** [comment]
We will close this one In favor of a different approach.

**Comment by michaelstaib** [comment]
For the new Client API approach look here #1011

**Pull request closed without merging**
