### PR TITLE
Updated IntrospectionQuery to conform to June 2018 spec

### PR DESCRIPTION
**Pull request by icanos**
- Updated IntrospectionQuery to conform to June 2018 __Directive Type spec (https://facebook.github.io/graphql/June2018/#sec-The-__Directive-Type)
- Replaced **onOperation**, **onFragment**, **onField** with **locations**

### CODE REVIEW

**Comment by michaelstaib** [comment]
Hi @icanos,

we actually have to do this differently.

We originally wanted to invest here more work but moved that back on our time table.

Let me give you an idea what we want to do here.

The stitching layer shall be compatible with older schemas. We actually already support more then the 2018 spec. In order to get this done we have to do two introspection calls.

1. We have to introspect the introspection schema and determine which version the remote schema is.
2. We send an introspection call that meets the the backend and map it to our schema.

At the moment I see three versions here. 2016 spec, 2018 spec, and the 2019 spec that introduces things like repeatable directives.

**Comment by michaelstaib** [comment]
It would be good to introduce an abstraction that represents the introspection handler. Would you still like to work on this?

**Comment by icanos** [comment]
I might be able to invest some time into this since this is a feature I am actually in need of. Currently solved it as my pull request suggests, but a proper fix would be better.

**Comment by michaelstaib** [comment]
Ok, I will create an issue an describe it.

**Comment by michaelstaib** [comment]
HI @icanos, sorry for letting you wait on this one. This week is really full and I try to push the new type system through. I will get back on this one tomorrow evening I think.

**Comment by michaelstaib** [comment]
@icanos we are fixing this issue with version 0.8.1 which will be out at 31st of March ...

**Comment by michaelstaib** [comment]
The feature can be tracked here https://github.com/ChilliCream/hotchocolate/issues/652

I will close this issue since we solved your issue with this.

**Comment by michaelstaib** [comment]
@icanos we have now released version 0.8.1-rc.3 which includes the 2-phase introspection

**Comment by icanos** [comment]
I will try it asap, thanks :)

**Comment by michaelstaib** [comment]
We are shipping the final version on Sunday...

**Pull request closed without merging**
