### PR TITLE
Make attributes inheritable again

### PR DESCRIPTION
**Pull request by tobias-tengler**
In #3812 we broke the following use case, since the `ExtendObjectType` attribute is no longer inherited:
```csharp
[ExtendObjectType(OperationTypeNames.Query)]
public class ExtensionBase
{}

public class InheritedExtension : ExtensionBase
{
    public string ExtendedField() => "Foo";
}

// ...

services
    .AddGraphQLServer()
    .AddQueryType()
    .AddTypeExtension<InheritedExtension>();
```

In this PR I made all attributes inheritable again (essentially undoing #3812) and added a test to cover the above use case.

### CODE REVIEW

**Comment by michaelstaib** [comment]
In this case also interface should be inheritable. Since it kind of feels strange that `ObjectTypeAttribute` will inherit but `InterfaceTypeAttribute` will not.

**Comment by michaelstaib** [comment]
Maybe revert the whole change, including the issue with the interface and move the problem to V12. We can break behavior there and rethink what we actually want to allow and why.

**Comment by tobias-tengler** [comment]
@michaelstaib I reverted the whole change.

I had to revert the change by hand instead of just reverting the entire commit, since it also did a bunch of other stuff, that would've caused merge conflicts. We should really try do more focused PRs in the future!
This is a topic for another day, but for similar reasons I'm also not very fond of the develop branch...

**Comment by michaelstaib** [comment]
Lets abandon this one. I have put a fix into v12.

**Pull request closed without merging**
