### PR TITLE
Improvements to AspNetCore Schema middleware

### PR DESCRIPTION
**Pull request by benmccallum**
- Added checksum support.
- Add HEAD verb support.

Addresses #2120

### CODE REVIEW

**Comment by benmccallum** [comment]
It seems like the solution doesn't currently build, which rings a bell as Peter mentioned in Slack the StarWars project wasn't compiling [here](https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1609942826072500).

So I've written some tests but we'll see if they work and I'll open this up for feedback anyway.

There might be a better way to avoid calculating the schema twice, by getting the checksum from the response's body stream, but I didn't want to cross-streams so to speak haha :P

Also, perhaps this would be better done in a standard HTTP way as an ETag or something by doing something like:
https://gist.github.com/madskristensen/36357b1df9ddbfd123162cd4201124c4

**Comment by michaelstaib** [comment]
Yeah, I think the ETag way would be the better route...

**Comment by benmccallum** [comment]
@michaelstaib, Perhaps the ETagging shouldn't be part of HC, that's just something folks can add themselves via that middleware I linked as per their own requirements. Maybe I just limit this PR  to support HEAD requests?

**Comment by benmccallum** [comment]
Then it's kind of pointless though, as you couldn't wrap this in other middleware to generate other useful headers if there's no body written... 

I think I should just abandon this entirely; as it's something can be done with separate middleware in a more standard way outside of HC.

Closing.

**Pull request closed without merging**
