### PR TITLE
Code documentation for most of IDiagnosticEvents et al

### PR DESCRIPTION
**Pull request by petli**
Summary of the changes (Less than 80 chars)

- Documented most of `IDiagnosticEvents` (skipped methods where I wasn't sure exactly what they do)
- Documented `IDiagnosticEventsListener`
- Documented `DiagnosticEventsListener`

No related issue.

### CODE REVIEW

**Comment by petli** [comment]
After digging through the code to find out how to use these interfaces in my code it seemed a waste not to also write down what I learned and submit it :)

**Comment by michaelstaib** [comment]
Awesome!

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
I chipped in some more documentation about the request context and the missing instrumentation events. Thanks so much for your work on this!

**Pull request merged**
