### PR TITLE
🚧Add attributes to filter and sorting

### PR DESCRIPTION
**Pull request by PascalSenn**
addreses: #1263

- [x] Remove Some Code Smells
- [x] Add Resources to Sorting

### CODE REVIEW

**Comment by michaelstaib** [comment]
This one is done but we should lift it to version 10 I think... since the attributes are coming in 10.
3

**Comment by michaelstaib** [comment]
What do we do with this one? Are you opening a new one?

**Comment by PascalSenn** [comment]
@michaelstaib  I will open new ones but want to keep this one because of the diff :+1: 
I'll remove it later

**Comment by michaelstaib** [comment]
can we close this one?

**Comment by PascalSenn** [comment]
@michaelstaib  yes but i still need to do this, so please let the issue alive for a bit longer :)

**Comment by michaelstaib** [comment]
Can I delete the branch or do you want to keep it?

**Comment by PascalSenn** [comment]
I will delete it once the feature is in place. 
I will add a task to the issue so we do not forget

**Pull request closed without merging**
