### PR TITLE
Add missing type error message

### LINKED ISSUE #5345: More concise error message when stitching errors occur
### Is your feature request related to a problem?

Hi.
We use the `stitching` functionality of the `HotChocolate` gateway and one issue that can occur during development and release is that when the gateway starts, if a type has been mis-typed in the stitching files, the error message sent by the Gateway is very long and lists all dependencies and types together in one long error message.
As an example - from a live project - but cut as it is so long:

> 1. Unable to resolve dependencies None: authorize, None: TypeQuotesInput!, None: delegate, None: Int, None: String, None: Int, None: String, None: [TypeManufacturerFilterInput!], None: TypeManufacturerFilterInput, None: delegate, None: BoilerInput!, None: delegate, None: Uuid!, None: delegate, None: CommunicationsInput!, None: delegate, None: Uuid!, None: delegate, None: String, None: delegate, None: delegate, None: Uuid!, None: delegate, None: Int!, None: delegate, None: Uuid!, None: delegate, None: delegate, None: BankInput, None: delegate, [...], None: FilterInput, None: [AuditLogEntitySortInput123!], None: delegate, None: Int, None: String, None: Int, None: String, None: delegate, None: WorkingDaysQueryInput!, None: delegate, None: Int, None: delegate for type `Query`. (HotChocolate.Types.ObjectType)

It is obvious in this example that the culprit is `AuditLogEntitySortInput123` as this is just an example of me breaking it, however in case of type renaming, issues can occur and in our micro services architecture can be a bit of a pain to fix.
Also there is no specific order - it would be better if the missing type appeared first or last, so that it can be easily pointed at.

### The solution you'd like

Show the missing types as an added error:
Missing types first
Full message (the original) set in this example

So essentially 2 errors, the first one only on the missing type(s).

I have tested a code change to solve this issue that I am happy to submit as part of this request.

### Product

Hot Chocolate

### PR DESCRIPTION
**Pull request by vmary2014**
Add a more concise error message when stitching errors occur

- Altered `TryNormalizeDependencies` to provide a list of `notFound` items of type `IReadOnlyList<ITypeReference>`
- Added an `Unable to find type(s) {0}` resource string

In the example provided in the original issue #5345 the error message added should be:

`1. Unable to find type(s) None: [AuditLogEntitySortInput123!] (HotChocolate.Types.ObjectType)`

And the second - original message - is kept and showing too.

Hope this is useful :+1: 

Closes #5345

### CODE REVIEW

**Comment by michaelstaib** [comment]
@vmary2014 thanks for contributing... 

Could you create a test that snapshots the error message.

**Comment by vmary2014** [comment]
> @vmary2014 thanks for contributing...
> 
> Could you create a test that snapshots the error message.

Hi @michaelstaib done. On my branch, aligned with the latest of version 12 I also added an integration test for the `HotCholocate.Stitching` project but it looks like this project is missing from the latest `main`. Once this is back I can add it later.

**Comment by vmary2014** [comment]
Thanks @michaelstaib for merging this. Do you know if it will make it to v12 too? Happy to raise a PR against your `main-version-12` branch if you wish.

**Comment by michaelstaib** [comment]
If you create a PR for the v12 branch I will merge it

**Comment by vmary2014** [comment]
> If you create a PR for the v12 branch I will merge it

Done here https://github.com/ChilliCream/hotchocolate/pull/5391

**Pull request merged**
