### PR TITLE
Add support for custom NodaTime patterns for serialization and deserialization

### PR DESCRIPTION
**Pull request by david-driscoll**
Summary of the changes (Less than 80 chars)

Currently NodaTime types are limited to specific patterns that can be accepted for deserialization. This makes it harder to allow more flexibility in deserialization, for example accept the default `DateTimeOffset` format and turn that into an `Instant` or `OffsetDateTime`.

- Any changes to the types should be opt-in, so existing behavior has been left alone.
- Only new constructors have been added.
- `OffsetDateTimeType` has been using `OffsetDateTimePattern.GeneralIso` for serialization but `OffsetDateTimePattern.ExtendedIso` for deserialization.  This behavior has been maintained (even if it might a bug)

Comments:
I'm not sure if you want the additional tests in other files, based on the file names not matching the test class names, I just simply left them in the same file.  This can ofc be changed.

### CODE REVIEW

**Comment by michaelstaib** [comment]
Thank you for contributing back ... @PascalSenn can you review?

**Review by PascalSenn — APPROVED** [review]
Great Pull request! Thanks a lot for this contribution! 

Just did some formatting changes and added validation for the input array (so that we do not get a index out of bounds if someone passes in an array)

**Comment by michaelstaib** [comment]
Sorry for the wait on this will have a look today.

**Comment by michaelstaib** [comment]
@david-driscoll this is damn good PR man! Sorry for not taking the time earlier. If you want to get more involved in this project I would be more than happy to have you.

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
@david-driscoll join us on slack: https://slack.chillicream.com

I have created a new release 12.7

**Comment by david-driscoll** [comment]
@michaelstaib I'm on the slack, and tend to lurk 😄

**Pull request merged**
