### PR TITLE
Added support for DateOnly and TimeOnly in MongoDB

### LINKED ISSUE #4648: The type of the member Date of the declaring type TransactionSummary is unknown
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hot Chocolate 12.4 added support for `DateOnly` and `TimeOnly` [posted here](https://chillicream.com/blog/2021/12/14/hot-chocolate-12-4/#dateonly-and-timeonly) but I'm getting:

```
The type of the member Date of the declaring type TransactionSummary is unknown
 (HotChocolate.Data.Filters.FilterInputType<Domain.Entities.TransactionSummary>)
```

This is the entity class:

```csharp
public class TransactionSummary : IEntity
{
    public string Id { get; set; } = default!;

    public DateOnly Date { get; set; }

    public string ReferenceId { get; set; } = default!;
}
```

This is the query:

```csharp
public class Query
{
    [UsePaging]
    [UseProjection]
    [UseSorting]
    [UseFiltering]
    public IExecutable<TransactionSummary> GetTransactionSummary([Service] IMongoCollection<TransactionSummary> collection)
        => collection.AsExecutable();
}
```

And finally, the services DI:

```csharp
builder.Services
	   .AddGraphQLServer()
	   .AddQueryType<Query>()
	   .AddMutationType<Mutation>()
	   .AddGlobalObjectIdentification()
	   .AddMongoDbFiltering()
	   .AddMongoDbSorting()
	   .AddMongoDbProjections()
	   .AddMongoDbPagingProviders();
```

### Steps to reproduce

1. Create a class with a property using `DateOnly` type.

### Relevant log output

```shell
An unhandled exception has occurred while executing the request.
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. For more details look at the `Errors` property.

1. The type of the member Date of the declaring type TransactionSummary is unknown
 (HotChocolate.Data.Filters.FilterInputType<Domain.Entities.TransactionSummary>)

   at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Additional Context?

Using latest version of Hot Chocolate + .NET 6 + Official MongoDB integration.

### Product

Hot Chocolate

### Version

12.5.0

### PR DESCRIPTION
**Pull request by daviddesmet**
Summary of the changes (Less than 80 chars)

- Added support for DateOnly and TimeOnly in MongoDB

Closes #4648 (The type of the member Date of the declaring type TransactionSummary is unknown)

### CODE REVIEW

**Review by PascalSenn — COMMENTED** [review]
Looks good :) 
Could you also add tests like in https://github.com/ChilliCream/hotchocolate/pull/4552/files? :)
The test setup will be slightly different, but there are already a log of tests in the mongo test repo.

**Comment by daviddesmet** [comment]
@PascalSenn Of course, I’ll work on them 😉

**Comment by daviddesmet** [comment]
@PascalSenn When working on the DateOnly tests I've noticed MongoDB C# driver still doesn't support DateOnly and TimeOnly times, there's an [open request here](https://jira.mongodb.org/browse/CSHARP-3717). Not sure how long it will take them to include it in the driver so the only way I see for the tests to pass is to create a custom Mongo Serializer until they add support for it, this should be called in the constructor for the tests, like so:

```csharp
public MongoDbFilterVisitorDateOnlyTests(MongoResource resource)
{
	Init(resource);

	var dateOnlySerializer = new DateOnlySerializer(true);
	if (!BsonClassMap.IsClassMapRegistered(typeof(Foo)))
	{
		BsonClassMap.RegisterClassMap<Foo>(cm =>
		{
			cm.AutoMap();
			cm.MapMember(c => c.Bar).SetSerializer(dateOnlySerializer);
		});
	}
}
```

This **RegisterClassMap** will have to be called for developers willing to support those types anyway.

I personally don't like to do this kind of workarounds in the tests. I would rather prefer to leave the tests prepared without such a workaround and when they support it, we can merge this PR. What do you think?

**Comment by PascalSenn** [comment]
@daviddesmet hmm i see, i personally do not mind the specific setup in the tests. I don't think we need to specify each property, i think it's enough to register the serializer for the type 

From the issue on Jira 
```csharp


BsonSerializer.RegisterSerializer(new DateOnlySerializer());
--
 
internal class DateOnlySerializer : StructSerializerBase<DateOnly>
{
   ....
}


```

**Comment by daviddesmet** [comment]
@PascalSenn sounds good, I will make the changes and update my PR.

**Comment by daviddesmet** [comment]
@PascalSenn I've added the DateOnly tests, feel free to check them out while I work on the TimeOnly tests.
Btw, would you also want me to add tests for comparisons? Like greater than, less than, etc?

**Comment by PascalSenn** [comment]
@davidsmet this looks very good! Will review ist ASAP!

**Comment by daviddesmet** [comment]
@PascalSenn aye! Let me know if you also want the comparisons tests. Btw, you mentioned another Smet :P

**Comment by daviddesmet** [comment]
@PascalSenn What's the format for passing a TimeSpan in the query? Afaik is ISO8601 but I'm still getting

```
TimeSpan cannot parse the given literal of type `StringValueNode`.
```

I've tried with below queries without any luck:

```graphql
{ root(where: { bar: { eq: \"06:30:00\" } }){ bar } }
```

```graphql
{ root(where: { bar: { eq: \"06:30:00.000\" } }){ bar } }
```

```graphql
{ root(where: { bar: { eq: \"6:30:00\" } }){ bar } }
```

```graphql
{ root(where: { bar: { eq: \"6:30:00.000\" } }){ bar } }
```

**Review by PascalSenn — APPROVED** [review]
Great addition! Just made a couple of formatting stuf, apart from that, we'll merge that as is! great job :)  
Thanks for the contribution!!

**Comment by daviddesmet** [comment]
It was my pleasure!

**Pull request merged**
