### PR TITLE
Fix Star Wars example

### LINKED ISSUE #3480: Broken Star Wars example
**Describe the bug**
The Star Wars example does not work out of the box and it also contains a release candidate of version 11.0.0 (11.0.0-rc.1). Upgrading to the latest version (11.1.0) does not solve the following issues:
1. No default filter convention found. Call `AddFiltering()` on the schema builder.
2. No default sorting convention found. Call `AddSorting()` on the schema builder.
3. The name `CharacterConnection` was already registered by another type. (HotChocolate.Types.Pagination.ConnectionType<HotChocolate.Types.InterfaceType<StarWars.Characters.ICharacter>>)

There are also some warnings about `ExtendObjectTypeAttribute.Name.set` being obsolete.

**To Reproduce**
Follow the steps in the [HotChocolate README](https://github.com/ChilliCream/hotchocolate/tree/main/src/HotChocolate).

**Expected behavior**
Example should work out of the box.

As this could be arguably the first experience a new developer has with HotChocolate, it should be a good experience. If I try a new library and the first example is already full of errors, I might reconsider and look for other options.

**Personal opinion**
This problem is one of many I've come to notice, ever since I tried to convince some colleagues to try out this project. "There is no (XML) documentation", "The example doesn't work", "The documentation is outdated", etc.

In my opinion the project should slow down in terms of features for a while and really focus on documentation/new-comer experience. All new and exciting features mean nothing if new developers have a hard time getting started and don't want to waste time looking into issues that shouldn't even be there in the first place. 
Hell, I've been using this library for a while and ever so often come across a comment in a PR that explains a really neat little feature, but it's not documented anywhere. `<url>?sdl` for example, such a convenient feature, but I have not seen it being mentioned anywhere in the documentation thus far.
I love this library, but it is really lacking in this aspect...

### PR DESCRIPTION
**Pull request by tobias-tengler**
Closes #3480

### CODE REVIEW

**Comment by tobias-tengler** [comment]
I think it would be great to also get rid of the `'ExtendObjectTypeAttribute.Name.set' is obsolete` warnings, but I couldn't find how I would do this properly. Maybe one of the core maintainers can chime in! ;)

**Review by michaelstaib — DISMISSED** [review]

**Comment by michaelstaib** [comment]
`[ExtendObjectType("Foo")]` instead of `[ExtendObjectType(Name = "Foo")]` will remove the obsolete messages.

**Comment by tobias-tengler** [comment]
Removed all the obsolete warnings! :)
I also took the liberty to change the obsolete message of the `SchemaType` on `UsePagingAttribute`. "Use Type" was misleading, since the setter is private so it actually can't be used as a replacement and the constructor should be used instead.

**Comment by michaelstaib** [comment]
@tobias-tengler I updated the build and replaced the attribute for friends with the new extension API. Also I am now using the operation constants on the attributes and simplified the startup.

**Comment by michaelstaib** [comment]
```
.AddQueryType()
                        .AddTypeExtension<CharacterQueries>()
                        .AddTypeExtension<ReviewQueries>()
                    .AddMutationType()
                        .AddTypeExtension<ReviewMutations>()
                    .AddSubscriptionType()
                        .AddTypeExtension<ReviewSubscriptions>()
```

**Comment by michaelstaib** [comment]
If you are happy with the PR I can merge it.

**Review by michaelstaib — APPROVED** [review]

**Comment by tobias-tengler** [comment]
Looks good to me! :)

**Pull request merged**
