### PR TITLE
Added Error, Payload and Input Helpers

### PR DESCRIPTION
**Pull request by PascalSenn**
This Pull Requests adds three new Features to HotChocolate to reduce boiler plate code. 
1. `[Error]` or `.Error()` that adds support for [Stage 6a Pattern of Marc-Andre Giroux](https://xuorig.medium.com/a-guide-to-graphql-errors-bb9ba9f15f85)
2. `[Payload]` or `.Payload()` that makes is easy to rewrite a return type to a Payload object 
3. `[Input]` or `.Input()` that combines arguments of resolvers into a input object 

This mutation

```c#

public class Mutation
{
    [Error(typeof(UserNameAlreadyTakeError))]
    [Error(typeof(UserNameValidationError))]
    [Payload]
    [Input]
    public User CreateUser([Service] IUserService service, string userName)
    {
       // ...
    }
}
```
results in this schema
```graphql
type Mutation {
  createUser(input: CreateUserInput!): CreateUserPayload!
}

input CreateUserInput {
  userName: String!
}

type CreateUserPayload {
  user: User 
  errors: [CreateUserError!]
}

type User {
  username: String
}
 
interface Error {
  message: String!
}
 
type UserNameAlreadyTakeError implements Error {
  message: String!
}
 
type UserNameValidationError implements Error {
  message: String!
}
 
union CreateUserError = UserNameAlreadyTakeError | UserNameValidationError
```
# `[Error]` or `.Error()`
The error extension helps you to create mutations that follow the
[Stage 6a Pattern of Marc-Andre Giroux](https://xuorig.medium.com/a-guide-to-graphql-errors-bb9ba9f15f85), without having to declare a lot of boilerplate.

The basic concept of the error middleware is to keep the resolver clean of any error handling code and use exceptions to signal a error state. The HotChocolate schema is automatically rewritten into the correct GraphQL pattern.
A middleware will catch all the exceptions and rewrite the output to the correct types.

> TIPP: You can use AggregateExceptions to return multiple errors

Example:
```c#

public class Mutation
{
    [Error(typeof(SomeSpecificDomainError))]
    [Error(typeof(SomeOtherError))]
    public CreateUserPayload CreateUser(CreateUserInput input)
    {
       // ...
    }
}

public record CreateUserInput(string UserName);

public record CreateUserPayload(User User);
```

```graphql
type Mutation {
  createUser(input: CreateUserInput!): CreateUserPayload!
}

input CreateUserInput {
  userName: String!
}

type CreateUserPayload {
  user: User
  # generated
  errors: [CreateUserError!]
}

type User {
  username: String
}

# generated
interface Error {
  message: String!
}

# generated
type SomeSpecificDomainError implements Error {
  message: String!
}

# generated
type SomeOtherDomainError implements Error {
  message: String!
}

# generated
union CreateUserError = SomeSpecificDomainError | SomeOtherDomainError

```

## Defining Errors
There are three ways to map an exception to a GraphQL error.

1. Map the exception directly
2. Map with a factory method (`CreateErrorFrom`)
3. Map with a constructor

### 1. Map the exception directly
The quickest way to define a GraphQL Error, is to map the exception directly into the graph. You can just annotate the exception directly on the resolver.

If the exception is thrown and reaches the middleware, the middlware will catch the exception and rewrite it to the error payload.

```c#
public class MyCustomException : Exception
{
     public MyCustomException():base("My custom message"){}
}

public class Mutation
{
    [Error(typeof(MyCustomException))]
    public CreateUserPayload CreateUser(CreateUserInput input)
    {
       // ...
    }
}
```

### 2. Map with a factory method (`CreateErrorFrom`)

If there should be any translation between exception and error, you can defined a classwith factory methods. These factory methods receive a exception and returnna object which will be used as the representation of the error
You can either use the constructor or the `CreateErrorFrom` factory method.

```c#
public class MyCustomError
{
    public static MyCustomError CreateErrorFrom(DomainExceptionA ex)
    {
        return new MyCustomError();
    }

    public static MyCustomError CreateErrorFrom(DomainExceptionB ex)
    {
        return new MyCustomError();
    }

    public string Message => "My custom error Message";
}

public class Mutation
{
    [Error(typeof(MyCustomError))]
    public CreateUserPayload CreateUser(CreateUserInput input)
    {
       // ...
    }
}
```
You can also define factories in a dedicated class.

```c#
public class CreateUserErrorFactory
{
    public static MyCustomErrorA CreateErrorFrom(DomainExceptionA ex)
    {
        return new MyCustomError();
    }

    public static MyCustomErrorB CreateErrorFrom(DomainExceptionB ex)
    {
        return new MyCustomError();
    }
}

public class Mutation
{
    [Error(typeof(CreateUserErrorFactory))]
    public CreateUserPayload CreateUser(CreateUserInput input)
    {
       // ...
    }
}
```

### 3. Map with a constructor
Instead of using factory methods, you can also use the constructor of the date transfer object directly.

```c#

public class MyCustomError
{
    public MyCustomError(MyCustomDomainException exception)
    {
        Message = exception.Message;
    }

    public MyCustomError(MyCustomDomainException2 exception)
    {
        Message = exception.Message;
    }

    public string Message { get; }
}

public class Mutation
{
    [Error(typeof(MyCustomError))]
    public CreateUserPayload CreateUser(CreateUserInput input)
    {
       // ...
    }
}
```
# GraphQL Inputs & Payload

Example:

```c#

public class Mutation
{
    [Payload]
    [Input]
    public User CreateUserAsync(
        [Service] IUserService service,
        string username,
        string name,
        string lastName)
        => userSerivce.CreateUser(username, name, lastName);
}
```

```graphql
type Mutation {
  createUser(input: CreateUserInput): CreateUserPayload
}

type CreateUserPayload {
  user: User
}

input CreateUserInput {
  username: String!
  name: String!
  lastName: String!
}
```

## Defining a payload

To define a payload you can either annotate the resolver with `[Payload(...)]` or use `.Payload(..)` if you use code
first types.

The `Payload` middleware is optimized for the use case of a single field on the payload.  If you need more than one field, you should define your custom payload object. The name of the field that holds the result, can be configured with the `name` parameter of the attribute/extension-method. By default the name is the name of the returned runtime type

```c#
public class Mutation
{
    [Payload("haveALookAtThis")] // <-------------
    public User CreateUserAsync(
        [Service] IUserService service,
        string username,
        string name,
        string lastName)
        => userSerivce.CreateUser(username, name, lastName);
}

```

Schema:

```graphql
type CreateUserPayload {
  haveALookAtThis: User
}
```

## Defining inputs

The `[Input]` annotation or the `.Input` extension method, can be used to combine arguments in a input object. By default all parameters of a method are combined into a input object and a argument is added.

```c#
public class Mutation
{
    [Input] // <-------------
    public User CreateUserAsync(
        [Service] IUserService service,
        string username,
        string name,
        string lastName)
        => userSerivce.CreateUser(username, name, lastName);
}

```

The default name of the argument is `input`. You can configure this with the `name` parameter.

```c#
public class Mutation
{
    [Input("custom")] // <-------------
    public User CreateUserAsync(
        [Service] IUserService service,
        string username,
        string name,
        string lastName)
        => userSerivce.CreateUser(username, name, lastName);
}

```

Schema:

```graphql
type Mutation {
  createUser(custom: CreateUserCustomInput): CreateUserPayload
}

type CreateUserPayload {
  user: User
}

input CreateUserCustomInput {
  username: String!
  name: String!
  lastName: String!
}
```

You can also define the `Input` annotation on arguments directly and define multiple inputs

```c#
public class Mutation
{
    public User CreateUserAsync(
        [Service] IUserService service,
        [Input("a")] string username,
        [Input("a")] string name,
        [Input("b")] string lastName)
        => userSerivce.CreateUser(username, name, lastName);
}
```

Schema

```graphql
type Mutation {
  createUser(a: CreateUserAInput, b: CreateUserBInput): CreateUserPayload
}

type CreateUserPayload {
  user: User
}

input CreateUserAInput {
  username: String!
  name: String!
}
input CreateUserBInput {
  lastName: String!
}
```
You can also override the method attribute, with a parameter attribute

```c#
public class Mutation
{
    public User CreateUserAsync(
        [Service] IUserService service,
        [Input("a")] string username,
        [Input("a")] string name,
        [Input("b")] string lastName)
        => userSerivce.CreateUser(username, name, lastName);
}
```

Schema:

```graphql
type Mutation {
  createUser(a: CreateUserAInput, b: CreateUserBInput): CreateUserPayload
}

type CreateUserPayload {
  user: User
}

input CreateUserAInput {
  username: String!
  name: String!
}

input CreateUserBInput {
  lastName: String!
}
```

### CODE REVIEW

**Comment by anadale** [comment]
@PascalSenn, what about using XmlDoc from mutation methods to pickup arguments (input fields) documentation and insert it into the schema?

**Comment by tobias-tengler** [comment]
> The problem i see is what does the `TypeName` do if you use it on args
> 
> ```
> public string CreateUser(
>    [Input(TypeName="CreateUserInput")] string firstName,
>    [Input(TypeName="OtherNameInput")] string LastName
> ```

What do you see as a problem here? In your own examples you are doing something similar:

> You can also define the Input annotation on arguments directly and define multiple inputs
> 
> ```csharp
> public class Mutation
> {
>     public User CreateUserAsync(
>         [Service] IUserService service,
>         [Input("a")] string username,
>         [Input("a")] string name,
>         [Input("b")] string lastName)
>         => userSerivce.CreateUser(username, name, lastName);
> }
> ```
> 
> Schema
> 
> ```graphql
> type Mutation {
>   createUser(a: CreateUserAInput, b: CreateUserBInput): CreateUserPayload
> }
> 
> type CreateUserPayload {
>   user: User
> }
> 
> input CreateUserAInput {
>   username: String!
>   name: String!
> }
> 
> input CreateUserBInput {
>   lastName: String!
> }
> ```

In my suggestion this would have the exact same effect, i.e. creating separate inputs, the only difference being that in your example you specify a substring and in my proposal you would specify the full input type name.

So the behavior I would desire would be the following:

```csharp
public class Mutation
{
    public User CreateUserAsync(
        [Service] IUserService service,
        [Input("CreateUserAInput")] string username,
        [Input("CreateUserAInput")] string name,
        [Input("CreateUserBInput")] string lastName)
        => userSerivce.CreateUser(username, name, lastName);
}
```

**Schema**

```graphql
type Mutation {
  createUser(a: CreateUserAInput, b: CreateUserBInput): CreateUserPayload
}

type CreateUserPayload {
  user: User
}

input CreateUserAInput {
  username: String!
  name: String!
}

input CreateUserBInput {
  lastName: String!
}
```

Albeit more verbose it gives full control over the name to the user.

**Comment by tobias-tengler** [comment]
I also took a look at Errors and I also really like it, I think this will be a really big feature for the library as it literally removes soooo much boilerplate.

There is one thing I'm not yet happy with though: The weakly typed error factory.
I'm not a fan of weakly typed stuff in general, since it's hard to evolve and hard to understand from a developer POV.

Imagine you are a new developer coming into a Hot Chocolate project and you see this:

```csharp
public class MyCustomError
{
    public static MyCustomError CreateErrorFrom(DomainExceptionA ex)
    {
        return new MyCustomError();
    }

    public static MyCustomError CreateErrorFrom(DomainExceptionB ex)
    {
        return new MyCustomError();
    }

    public string Message => "My custom error Message";
}

public class Mutation
{
    [Error(typeof(MyCustomError))]
    public CreateUserPayload CreateUser(CreateUserInput input)
    {
       // ...
    }
}
```

_Are these factory methods remains of old tests that weren't cleaned up? They aren't used anywhere - might as well get rid of them..._

Although more verbose, I think it would be better to have an interface for this:

```csharp
// name is probably to generic
public interface IErrorFactory<TError> // where TError : Exception
{
    TError CreateErrorFrom(Exception exception);
}

public class MyCustomError
{
    public string Message => "My custom error Message";
}

public class MyErrorFactory : IErrorFactory<MyCustomError>
{
    public MyCustomError CreateErrorFrom(Exception exception)
    {
        // ...
    }
}
```

Also for the multiple overloads for specific exception types, I don't think Hot Chocolate has to cover for this. The user can handle the specificity of the exceptions himself:

```csharp
public class MyErrorFactory : IErrorFactory<MyCustomError>
{
    public MyCustomError CreateErrorFrom(Exception exception)
    {
        if (exception is DomainExceptionA)
        {
            // ...
        }
    }
}
```

This would require to have a separate factory always for this scenario, which is a bummer, but I think the added explicitly is worth it IMO.



This is definitely out of scope for a first release, but in a perfect world I would wish to be able to switch between stage 6, stage 6a and potentially other variants of error handling that are automatically generated.

**Comment by Ciantic** [comment]
This looks cool. One note, I don't understand why this is object type: 

```graphql
type CreateUserPayload {
  user: User 
  errors: [CreateUserError!]
}
```

In my opnion it should be union type:

```graphql
type UserErrors {
  errors: [CreateUserError!]
}
union CreateUserPayload = User | UserErrors
```

I think of errors or successes like the discriminated unions in F#/Haskell etc.

**Comment by tobias-tengler** [comment]
The issue with returning a union is the evolvability of the schema. Imagine a new error is added. Every client now needs to update their queries to also query for this error, otherwise it is lost. Having a list of errors defined by an interface ensures that clients are able to handle every future error to at least some extend.

I'd recommend reading the following for a comparison of the different approaches to error handling: https://productionreadygraphql.com/2020-08-01-guide-to-graphql-errors

Personally I also sometimes prefer just returning a union, but that's mostly because I'm working on a project with a single client where we deploy both it and the server silmutaneously. As a general coverage of errors stage 6a is definitely the best, so I agree with the coice of it being the default. As I noted in one of my above comments I would also love to have the option to toggle how errors are handled in a later version. For the first version of this feature stage 6a is definitely the best choice.

**Comment by Ciantic** [comment]
There is no evolvability issues in this format: 

```
type UserErrors {
  errors: [CreateUserError!]
}
union CreateUserPayload = User | UserErrors
```

To my knowledge, you can just add new error types just as easily. This is used in other languages e.g. in Haskell you can use applicative and accumulate errors on the left side.

**Comment by damikun** [comment]
@Ciantic With approach you presented is not as easy for frontend engineers to use generated types.. You than need to use `__typename` or fragmnets on type to evaluate returned type... What you wanna on generated types is separately have `response` and `errors` prop....

Another think with this union you cannot implement `IBaseError` to group interface across errors since you have User there

**Comment by Ciantic** [comment]
@damikun I guess the difficulty of using the errors depends on the client. I have actually come around to the null/or errors currently proposed. We've discussed this in the Slack at the same time.

I wish there were just one way to return errors or the result from the mutations, in the GraphQL spec itself. Then it could be mapped in F# to Result, in C# client to exceptions etc. Now it's just left for all graphql tools to invent this error mapping themselves.

**Comment by thomastvedt** [comment]
Hi, this looks really great! I want it right now 😅🚀 
I was just about to start on a bunch of boilerplate for this.. This PR will save me a bunch of work, looking forward to it! 🎂

**Comment by michaelstaib** [comment]
We have created a new PR for this one.

**Pull request closed without merging**
