### PR TITLE
Fixes a bug that causes an ArgumentExceptions when roles are used to authorize.

### PR DESCRIPTION
**Pull request by leighmetzroth**
Fixes a few bugs in the authorize directive and middleware

- Fixed the typo in the policy not found error code
- Fixed a bug in the authorize directive where passing in only roles would cause an error to be thrown

Addresses a bug I haven't raised as it was easier to fix than to try and explain it.

### CODE REVIEW

**Comment by michaelstaib** [comment]
> Fixed a bug in the authorize directive where passing in only roles would cause an error to be thrown

Which bug is that? Can you elaborate?

**Comment by michaelstaib** [comment]
OK, I see what you attempted to fix... but in this case rewrite it to `readOnlyRoles.Count == 0`.

**Comment by michaelstaib** [comment]
Also we need a test for that so that this behavior is under test.

**Comment by leighmetzroth** [comment]
Thanks for the info on Linq Any, I was led to believe it was faster than using counts. "This changes everything!" lol

When I'm back home I'll change it to readOnlyRoles.Count == 0 as the > 0 does not seem correct as that would infer you can never match on roles, only policies.

**Comment by michaelstaib** [comment]
I want to get rc.3 out so I have added the tests and rewrote your fix to use count. Thanks for your PR I will merge it now.

**Comment by michaelstaib** [comment]
OK, we have that now under test. 100% coverage on the changed code... so I will merge that now.

**Comment by leighmetzroth** [comment]
Awesome, and I'm so pleased that you're getting these releases out so quickly.

**Pull request merged**
