### PR TITLE
Add GetPagingArguments to the ResolverContext

### LINKED ISSUE #3557: Add GetPagingArguments method to IResolverContext
At the moment I have to get arguments like "first" from the context myself.
```csharp
var first = context.ArgumentValue<int?>("first");
```

All of this is already handled inside the [PagingHandlers](https://github.com/ChilliCream/hotchocolate/blob/7f854213728a88209da6b7543cbc8666843a1853/src/HotChocolate/Core/src/Types.CursorPagination/CursorPagingHandler.cs#L39). We could extract this logic and make it accessible to consumers of the library.

I propose to add a new extension method like `GetPagingArguments` to the `IResolverContext`, which would return the `CursorPagingArguments`. (`GetOffsetPagingArguments` respectively)

This would match `AddPagingArguments` nicely and would reduce boilerplate.

I think it could also be helpful, if these methods validate the arguments against the configured `PagingOptions`, i.e. `DefaultPagingSize` and `MaxPagingSize`.

### PR DESCRIPTION
**Pull request by tobias-tengler**
When working with `AddPagingArguments` you can now easily retrieve all these arguments, by calling:
```csharp
descriptor
    .Field("users")
    .AddPagingArguments()
    // ...
    .Resolve(context =>
    {
        CursorPagingArguments arguments = context.GetPagingArguments();

        // ...
    });
```
There's a new extension method for usage with `AddOffsetPagingArguments` as well: `context.GetOffsetPagingArguments()`.

Closes #3557

### CODE REVIEW

**Comment by tobias-tengler** [comment]
Not sure why this one test was failing before, but I've reverted all areas, where this breakage could've come from, even though I couldn't see any breaking changes...
Also a lot of tests of the Core package are failing for me, when I execute them In Visual Studio. Also on the main branch. Not sure what's up with that.

I'm also not sure yet, how I would handle PagingOptions with my approach. Let me mark this as draft again...

**Comment by tobias-tengler** [comment]
Any good ideas on how I could access the PagingOptions configured for the middleware inside the resolver? I thought about using the context, but the global PagingOptions are already on there.

**Comment by michaelstaib** [comment]
Is the his ready for review?

**Comment by tobias-tengler** [comment]
> Is the his ready for review?

Nope, I actually forgot about this PR, since I couldn't solve it with the old pagination API. Will revisit in the coming days.

**Comment by sergiu-enache** [comment]
hi @tobias-tengler did you figure out how to access PagingOptions from a resolver? I am facing a similar issue.
Also how do you get the global PagingOptions from the context?

**Pull request closed without merging**
