### PR TITLE
Treat `Task<IQueryable/IExecutable>` properly in UseDbContext

### PR DESCRIPTION
**Pull request by JakeSmokie**
Fix that unwraps Task<> from result type in UseDbContext

Addresses #2754

### CODE REVIEW

**Comment by michaelstaib** [comment]
I have reworked your code to also allow support for `ValueTask`. 

Moreover, I added some unit tests so that the code is properly under test.

**Review by michaelstaib — APPROVED** [review]

**Comment by gojanpaolo** [comment]
In graphql-workshop session # 3 Understanding GraphQL query execution and DataLoader, a `ToListAsync` was applied that avoids an `ObjectDisposedException` (it was not explicitly mentioned that that is the main reason but I believe it is). 
Jump to # 7 here: https://github.com/ChilliCream/graphql-workshop/blob/master/docs/3-understanding-dataLoader.md#configure-field-scoped-services

```c#
[UseApplicationDbContext]
public Task<List<Speaker>> GetSpeakers([ScopedService] ApplicationDbContext context) =>
    context.Speakers.ToListAsync();
```

Does this PR fix the exception if we remove the `ToListAsync` and leave the `IQueryable`?
I'll retest when 11.1 gets released.

```c#
[UseApplicationDbContext]
public IQueryable<Speaker> GetSpeakers([ScopedService] ApplicationDbContext context) =>
    context.Speakers;
```

**Comment by PascalSenn** [comment]
yes this should actually be available in 11.0.7

**Comment by gojanpaolo** [comment]
It looks like the issue I described is not yet fixed as of 11.0.7. I created a sample repo: https://github.com/gojanpaolo/hc-1
All the essential code is in [Startup.cs](https://github.com/gojanpaolo/hc-1/blob/main/WebApplication1/WebApplication1/Startup.cs)

With the following lines as the main issue:
https://github.com/gojanpaolo/hc-1/blob/62b32d5671f50a2acaa0093da788230a7dbaa284/WebApplication1/WebApplication1/Startup.cs#L35-L36

To reproduce

Run the following query

```graphql
{
  speakers {
    id
  }
}
```

and you'll get the following result

```json
{
  "errors": [
    {
      "message": "Unexpected Execution Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "speakers"
      ],
      "extensions": {
        "message": "Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.\r\nObject name: 'ApplicationDbContext'.",
        "stackTrace": "   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()\r\n   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()\r\n   at Microsoft.EntityFrameworkCore.DbContext.get_Model()\r\n   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()\r\n   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()\r\n   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()\r\n   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.IEnumerable.GetEnumerator()\r\n   at HotChocolate.Execution.Processing.ResolverTask.<>c__DisplayClass13_0.<ExecuteResolverPipelineAsync>b__0()\r\n   at System.Threading.Tasks.Task`1.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location ---\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Execution.Processing.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"
      }
    }
  ],
  "data": {
    "speakers": null
  }
}
```

**Comment by StuwiiDev** [comment]
I had the same problem but then I added services.AddScoped<Query>(); to the startup file. The actual error was disguised by the one above and it doesn't mention it in the newest documentation.
Query for me was the basic one shown in the official docs

**Pull request merged**
