### PR TITLE
Fix stitching serialization invalid json #2024 #1972

### LINKED ISSUE #1972: Stitched variable of type [Long!] and [Int!] are concatenated.
**Describe the bug**
Hi, i recently got an issue with a stitched schema. My [Long!] content is getting concatenated to a array of one item (concatenation of all items). I've been able to notice that on version 10.3.6 and 10.4.3 (latest release).
I've been able to test some things :
- [Long!] and  [Int!] are not working [1,2,3,4,5,6] => [123456]
- Input types are also not working  { "values": [1, 2, 3 ]  } =>  { "values": [123 ]  }

- [String!] is working fine ["1","2","3","4","5","6"] => ["1","2","3","4","5","6"]
- [Boolean!] is also working fine [true, false, true] =>  [true, false, true] 

Stitched variable of type [Long!] and [Int!] are concatenated.

**To Reproduce**
```
query GetMyData($Ids: [Long!]) {
    myfield {
        mystitchedfield(ids: $Ids) {
          count
        }
    }
}

arguments
{
 "Ids": [1,2,3,4,5,6]
}
```
this requests when stitched will send [123456] to the server instead of [1,2,3,4,5,6]

**Expected behavior**
An array of 5 Scalar elements should not be concatenated into an array of 1 element

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10.4.3

**Additional context**
https://github.com/erwan-joly/HotChocolateStitchingBug
this bug is shown in this small repo. To use it
```
query ($ids: [Int!]) {
    getids(ids: $ids)
}
```
with arguments
```
{
	"ids": [
		1,
		2,
		3
	]
}
```

when post to http://localhost:5050 the result is 
```
{
  "data": {
    "getids": [
      123
    ]
  }
}
```
when post to http://localhost:5051 the result is
```
{
  "data": {
    "getids": [
      1,
      2,
      3
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by erwan-joly**
Same as https://github.com/ChilliCream/hotchocolate/pull/2025 without Convert.ToInt32

Fixes #1972

### CODE REVIEW

**Comment by michaelstaib** [comment]
Hi, thanks for the effort on this one.

**Comment by michaelstaib** [comment]
@erwan-joly  are you on version 10 or 11?

**Comment by erwan-joly** [comment]
> @erwan-joly  are you on version 10 or 11?

I’m on version 10.4.3

**Comment by michaelstaib** [comment]
@erwan-joly The master branch is version 11. 

Can you also do this fix on version 10, which is in branch "version_10_0_0_master"? The structure has changed so much that we cannot merge the change into version 10 automatically. 

For version 11, I will merge it now. However, we will, I think, entirely rework this part for 11 since it is not ideal and clean to do it like that. With that, I do not mean the fix itself but how we handled this part in the first place.
Thanks for your help with this.

**Comment by michaelstaib** [comment]
@PascalSenn fyi

**Pull request merged**
