### PR TITLE
Add Automatic Drafting of Release Notes

### PR DESCRIPTION
**Pull request by RehanSaeed**
The releases created by this repo have no information in them about what PR was completed. This PR adds [release-drafter](https://github.com/release-drafter/release-drafter) which automatically drafts release notes but does require you to use the following GitHub labels on your PR's:

Apply one or more of the following to determine the heading the PR will come under:

- 📚 documentation
- 🌶️ banana cake pop
- 🌶️ green donut
- 🌶️ hot chocolate
- 🌶️ marshmallow pie
- 🌶️ strawberry shake
- 🌶️ website
- 🧰 maintenance

`🧰 maintenance` is a new label that will need to be created. I find this label useful for miscellaneous PR's that don't fit under any other category.

You can also apply the following labels (which would need to be created) which automatically increments the major, minor or patch version number in the draft release. I'm not sure you need this part since I'm not sure how you do versioning.

- major
- minor
- patch

For a full walkthrough of how all this works, you can check out my blog post:

https://rehansaeed.com/the-fastest-nuget-package-ever-published-probably/

BTW, the release-drafter build will fail in this PR because there is no release-drafter.yml file checked into the main branch yet.

### CODE REVIEW

**Comment by michaelstaib** [comment]
Why is the release drafter breaking?

**Comment by RehanSaeed** [comment]
The release-drafter build will fail in this PR because there is no release-drafter.yml file checked into the main branch yet.

**Comment by RehanSaeed** [comment]
Is the versioning story OK?

**Comment by michaelstaib** [comment]
cc @PascalSenn

**Comment by PascalSenn** [comment]
Looks good to me :) Thanks for putting this together!

**Pull request merged**
