### PR TITLE
Update GraphiQL middleware

### PR DESCRIPTION
**Pull request by akaSybe**
#564 

added GraphiQL app and bundling via webpack, so now we know exactly which versions of libraries middleware uses

### CODE REVIEW

**Comment by akaSybe** [comment]
Don't merge yet please. I will ask frontend developers at work, if we still need to add promise/fetch polyfill even if we use babel.

**Comment by akaSybe** [comment]
@michaelstaib could you please test AspNetClassic version. I work on Macbook Air, so I can't test AspNetClassic

**Comment by michaelstaib** [comment]
@akaSybe  I am using a MacBook Pro :) But @rstaib can do it.

**Comment by akaSybe** [comment]
@rstaib ready to review

**Comment by michaelstaib** [comment]
HI @akaSybe, we have decided to not update GraphiQL. Sorry that you did all that work for nothing here. We are focusing on Playground and our own UI for the next releases.

**Pull request closed without merging**
