### PR TITLE
Add support for eui-64 mac addresses for MacAddress scalar type

### PR DESCRIPTION
**Pull request by oising**
- Update MacAddressType validation regex to manage 64 bit formats (colon, hyphen and dotted-quad)
- Update tests to add inline data for the above formats
- Update resx localisations

regex:
image

### CODE REVIEW

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
image

**Comment by michaelstaib** [comment]
@oising the tests seem to fail for the scalar.

**Review by michaelstaib — CHANGES_REQUESTED** [review]
@oising the tests seem to fail for the scalar.

**Comment by oising** [comment]
> @oising the tests seem to fail for the scalar.

Forgot to update the snapshot. Done!

**Review by oising — COMMENTED** [review]
(ignore this)

**Comment by PascalSenn** [comment]
@oising  The PR looks good! :) 
Can you also update the docs? https://github.com/ChilliCream/hotchocolate/blob/main/website/src/docs/hotchocolate/defining-a-schema/scalars.md

**Comment by oising** [comment]
> @oising The PR looks good! :)
> Can you also update the docs? https://github.com/ChilliCream/hotchocolate/blob/main/website/src/docs/hotchocolate/defining-a-schema/scalars.md

Doh.. of course! I also noticed grammar/typo issue.

Done!

**Review by PascalSenn — APPROVED** [review]

**Comment by oising** [comment]
@michaelstaib Do you need to review again? It says "requested changes" blocking. I'm not sure there's anything left to do.

**Review by michaelstaib — DISMISSED** [review]

**Comment by oising** [comment]
Am I meant to resolve these merge conflicts or is that your job, guys? @PascalSenn @michaelstaib

**Review by tobias-tengler — APPROVED** [review]
@oising If you resolve the conflicts with the current master, I think we can get this merged! :)

**Review by tobias-tengler — APPROVED** [review]
The Sonar failure is caused by flaky tests, so I think we can get this merged!

**Comment by michaelstaib** [comment]
ok ... lets merge 👯

**Pull request merged**
