### PR TITLE
Separate code generation from analyzer

### PR DESCRIPTION
**Pull request by benmccallum**

### CODE REVIEW

**Comment by benmccallum** [comment]
@michaelstaib , still a work in progress, but how do you feel about CodeGeneration as a name?

I noticed MS use `Microsoft.CodeAnalysis` to contain all the Roslyn APIs, but I don't think that makes much sense and probably is just because the evolved code generation into analyzers.

Other than that I just need to make sure it all works tomorrow or Sunday and then we can merge.

**Comment by benmccallum** [comment]
Things to review/discuss:
1. Have written a basic snapshooter test, but we need a better solution to make it readable.
2. The interface. Prob needs to be renamed to `ICodeGenerator` and the method take a `CodeGeneratorContext`, but I'm not 100% sure the EF one would share the same interface. Right now it would work though, so we can.
3. Naming, is everyone ok with `HotChocoloate.CodeGeneration`?

**Comment by michaelstaib** [comment]
Will have a look

**Comment by michaelstaib** [comment]
looks already good. when do we want to chat?

**Pull request merged**
