### PR TITLE
Fix stitching serialization invalid json #2024 #1972 on v10

### PR DESCRIPTION
**Pull request by erwan-joly**
same as https://github.com/ChilliCream/hotchocolate/pull/2086 for v10

### CODE REVIEW

**Comment by erwan-joly** [comment]
@michaelstaib are the tests expected to fail ? this is exactly the same code in https://github.com/ChilliCream/hotchocolate/pull/2086

**Comment by michaelstaib** [comment]
Sonar, yes.... since it is pushing the code changes against the sonar 11 result. Do not worry about that. This is gonna be one of the last updates to the 10 core.

**Comment by michaelstaib** [comment]
I have to do one more fix and for 10 and then I will create a preview ... .are you on our slack channel?

**Comment by erwan-joly** [comment]
I am now Erwan Joly

**Pull request merged**
