### PR TITLE
Fixes ambiguous Nullable Attribute

### PR DESCRIPTION
**Pull request by jonmill**
Fixes nullability checking to only look for the .NET Framework Nullable attribute

Addresses #1976

### CODE REVIEW

**Comment by jonmill** [comment]
@PascalSenn - looks like a CI run had failed infrastructure (.NET crashed). Can we re-run it please?

**Comment by jonmill** [comment]
@PascalSenn  - just a ping about re-running the failed CI due to infrastructure :)

**Comment by jonmill** [comment]
@PascalSenn - got CI to run by closing + re-opening the PR and things look to be green!

**Comment by michaelstaib** [comment]
I will have a look.

**Comment by michaelstaib** [comment]
@PascalSenn do we need this on version 10 as well?

**Comment by michaelstaib** [comment]
@jonmill thanks for your contribution. We value your effort. This one will be merged today into version 11.

**Comment by michaelstaib** [comment]
Fix for version 10 is here: #1982

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/releases/tag/11.0.0-preview.131

**Comment by michaelstaib** [comment]
Welcome as 47th contributor to Hot Chocolate 🎉

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/releases/tag/10.5.0-preview.3

**Comment by jonmill** [comment]
@michaelstaib thanks for taking a look! I appreciate the quick turnaround!

**Pull request merged**
