### PR TITLE
Implemented Url scalar type

### LINKED ISSUE #61: URL Scalar
The URL scalar is not a type of the specification. Nevertheless, the specification mentions it as a "potentially useful custom scalar".

We agree with this and want to provide this typ as one of our extended built-in type.

The URL type shall serialise as string and the hot chocolate GraphQL server guarantees that it is a valid URL. The native type representation should be System.Uri and we should provide a converter also have a System.String representation.

### PR DESCRIPTION
**Pull request by shemanaev**
This pr fixes #61

### CODE REVIEW

**Comment by michaelstaib** [comment]
Hi @shemanaev, thanks for your contribution.

**Comment by michaelstaib** [comment]
- [ ] Sonar Passed
- [ ] Tests Passed
- [ ] Better Code Hub Passed

**Comment by shemanaev** [comment]
@michaelstaib wow, you fast. Just walked away to make some tea and boom! merged 😄

**Comment by TristanTDev** [comment]
Hi, just wondering what exactly the format of URL's need to be for the Scalar? Currently trying to send a mutation with this segment

{
  website: "https://www.google.com"
}

And getting an error The specified value type of field `website` does not match the field type.", am I formatting this incorrectly?

**Comment by michaelstaib** [comment]
looks fine to me :) hmmm let me look at the tests.

**Comment by michaelstaib** [comment]
Also, did you see that we have a slack channel: 
https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q

**Comment by TristanTDev** [comment]
Ah cheers that's even better thank you!

**Pull request merged**
