### PR TITLE
Add non-generic IClientBuilder

### LINKED ISSUE #3980: [StrawberryShake] Provide non-generic `IClientBuilder`
**Is your feature request related to a problem? Please describe.**
I'm creating my own overloads for dependency injection registration, and would like to return a `IClientBuilder` so that clients can further configure (after the library has applied default configuration). However, the store is an implementation detail (and it's also use-less as I'm building store-less), so I would like to hide that. 

**Describe the solution you'd like**
I suggest creating a simple `IClientBuilder` and having `IClientBuilder<TStore> : IClientBuilder`. Then moving all extension methods that doesn't require the `TStore` to use the non-generic variant directly.

**Describe alternatives you've considered**
I don't know if there are any good alternatives available. I could create my own interface which forwards to the inner one, but that would mean that I would have to copy all extension methods myself. It's not really a workable solution.

### PR DESCRIPTION
**Pull request by Alxandr**
Add non-generic IClientBuilder

Closes #3980

### CODE REVIEW

**Comment by michaelstaib** [comment]
I think we want to get rid of the generic one altogether. It essentially was a crutch. We should no longer need this with the new DI functions that we have integrated. So essentially now a user should be able to access the inner services and by thus get access to the store accessor.

**Comment by Alxandr** [comment]
It's (as it stands) required for at least one of the extension methods. However, that can probably be reworked. I'll take a look at it tomorrow.

**Comment by michaelstaib** [comment]
Yes, I can give you some code hints tomorrow. We essentially have a helper to get this. I kind of never like that we added this generic :)

**Comment by Alxandr** [comment]
I removed the generic variant, however this has implications on the generated code (hence I also tried to modify the code generator). However, due to things not working as it should on my computer, I can't run the tests locally (all of them fail), so I need help to finish this. Typically updating snapshots and whatnot.

**Comment by michaelstaib** [comment]
I will do ... But ... I am rather destroyed today after a nightshift with @PascalSenn  :)

**Comment by michaelstaib** [comment]
This one will be integrated into preview 27 today.

**Pull request closed without merging**
