### PR TITLE
Introduce HotChocolate.Data.AutoMapper

### PR DESCRIPTION
**Pull request by PascalSenn**
Adds the Package HotChocolate.Data.AutoMapper that has an extension method to project an IQueryable based on the IResolverContext and Projections

### CODE REVIEW

**Comment by nkovacic** [comment]
Much needed, awesome.

**Review by michaelstaib — APPROVED** [review]

**Comment by gmavritsakis** [comment]
Excellent work!
Thank you so much @PascalSenn and @michaelstaib !

**Comment by gmavritsakis** [comment]
Guys this seems to not be working.
Did someone else used it successfully ?

**Comment by gmavritsakis** [comment]
Unfortunately when using HotChocolate.Data.AutoMapper ProjectTo make things even worse!

Now all the properties of the object hierarchy are fetched, regardless the query!

Considering this query:
```
query {
  myClient {
    clientKey
  }
}
```
using plain automapper projections:

```
SELECT [a].[Balance] AS [CurrentBalance]
FROM [Clients].[Client] AS [c]
INNER JOIN [Accounts].[Account] AS [a] ON [c].[CurrentAccountId] = [a].[AccountId]
WHERE [c].[ClientId] = @___currentUser_ClientId_0
```

using the new HotChocolate.Data projection:

```
      SELECT [c].[ClientPublicKey], [a].[Balance], CASE
          WHEN [c0].[ClientProfileId] IS NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END, [c0].[AddressLine], [c0].[AddressLine1], CASE
          WHEN [c0].[AvatarFileName] IS NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END, [c0].[AvatarFileName], [c0].[City], CASE
          WHEN [c1].[CountryId] IS NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END, [c1].[CountryCode], [c1].[CountryId], [c1].[DisplayName], [c1].[PhonePrefix], [c0].[CountryId], [c0].[DiscoverableByTag], [c0].[Email], [c0].[FirstName], [c0].[FullName], [c0].[LastName], [c0].[Mobile], CASE
          WHEN [c2].[CountryId] IS NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END, [c2].[CountryCode], [c2].[CountryId], [c2].[DisplayName], [c2].[PhonePrefix], [c0].[MobileRegistrationCountryId], [c0].[PostalCode], [c0].[ThrooTag], [c0].[UseBiometrics], [c0].[UsePushNotifications]
      FROM [Clients].[Client] AS [c]
      INNER JOIN [Accounts].[Account] AS [a] ON [c].[CurrentAccountId] = [a].[AccountId]
      LEFT JOIN [Clients].[ClientProfile] AS [c0] ON [c].[ClientId] = [c0].[ClientId]
      LEFT JOIN [Lists].[Country] AS [c1] ON [c0].[CountryId] = [c1].[CountryId]
      LEFT JOIN [Lists].[Country] AS [c2] ON [c0].[MobileRegistrationCountryId] = [c2].[CountryId]
      WHERE [c].[ClientId] = @___currentUser_ClientId_0
```



Of course, by the time we request event one field from a nested object, both of them will expand and over-fetch all object details:

```
query {
  myClient {
    clientKey
    profile{
      id
    }
  }
}
```

using plain automapper projections:

```
SELECT [c].[ClientPublicKey], CASE
          WHEN [c0].[ClientProfileId] IS NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END, [c0].[AddressLine], [c0].[AddressLine1], CASE
          WHEN [c0].[AvatarFileName] IS NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END, [c0].[AvatarFileName], [c0].[City], CASE
          WHEN [c1].[CountryId] IS NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END, [c1].[CountryCode], [c1].[CountryId], [c1].[DisplayName], [c1].[PhonePrefix], [c0].[CountryId], [c0].[DiscoverableByTag], [c0].[Email], [c0].[FirstName], [c0].[FullName], [c0].[LastName], [c0].[Mobile], CASE
          WHEN [c2].[CountryId] IS NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END, [c2].[CountryCode], [c2].[CountryId], [c2].[DisplayName], [c2].[PhonePrefix], [c0].[MobileRegistrationCountryId], [c0].[PostalCode], [c0].[ThrooTag], [c0].[UseBiometrics], [c0].[UsePushNotifications], CASE
          WHEN [c0].[ClientProfileId] IS NULL THEN NULL
          ELSE N'MyProfile'
      END
      FROM [Clients].[Client] AS [c]
      LEFT JOIN [Clients].[ClientProfile] AS [c0] ON [c].[ClientId] = [c0].[ClientId]
      LEFT JOIN [Lists].[Country] AS [c1] ON [c0].[CountryId] = [c1].[CountryId]
      LEFT JOIN [Lists].[Country] AS [c2] ON [c0].[MobileRegistrationCountryId] = [c2].[CountryId]
      WHERE [c].[ClientId] = @___currentUser_ClientId_0

```

using the new ProjectTo extension:

```
      SELECT [c].[ClientPublicKey], [a].[Balance], CASE
          WHEN [c0].[ClientProfileId] IS NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END, [c0].[AddressLine], [c0].[AddressLine1], CASE
          WHEN [c0].[AvatarFileName] IS NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END, [c0].[AvatarFileName], [c0].[City], CASE
          WHEN [c1].[CountryId] IS NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END, [c1].[CountryCode], [c1].[CountryId], [c1].[DisplayName], [c1].[PhonePrefix], [c0].[CountryId], [c0].[DiscoverableByTag], [c0].[Email], [c0].[FirstName], [c0].[FullName], [c0].[LastName], [c0].[Mobile], CASE
          WHEN [c2].[CountryId] IS NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END, [c2].[CountryCode], [c2].[CountryId], [c2].[DisplayName], [c2].[PhonePrefix], [c0].[MobileRegistrationCountryId], [c0].[PostalCode], [c0].[ThrooTag], [c0].[UseBiometrics], [c0].[UsePushNotifications]
      FROM [Clients].[Client] AS [c]
      INNER JOIN [Accounts].[Account] AS [a] ON [c].[CurrentAccountId] = [a].[AccountId]
      LEFT JOIN [Clients].[ClientProfile] AS [c0] ON [c].[ClientId] = [c0].[ClientId]
      LEFT JOIN [Lists].[Country] AS [c1] ON [c0].[CountryId] = [c1].[CountryId]
      LEFT JOIN [Lists].[Country] AS [c2] ON [c0].[MobileRegistrationCountryId] = [c2].[CountryId]
      WHERE [c].[ClientId] = @___currentUser_ClientId_0
```

Tested with 

HotChocolate.Data.AutoMapper v12.6.0
AutoMapper.Extensions.Microsoft.DependencyInjection v11.0.0 / 8.1.1 / 8.1.0 / 8.0.1

**Comment by PascalSenn** [comment]
It seems to be a regression in automapper, simple projections wuthou filtering and sorting are working in with atuomapper version 10.1

**Comment by gmavritsakis** [comment]
Hi @PascalSenn 
You are right, I have forgotten then ExplicitExpansion.

Unfortunately, having set that for all my models, something like this:

```
            CreateMap<Country, CountryViewModel>(MemberList.Destination).
                ForAllMembers(opt => opt.ExplicitExpansion());

            CreateMap<MerchantEmployeeProfile, MerchantEmployeeProfileViewModel>(MemberList.Destination).
                ForAllMembers(opt => opt.ExplicitExpansion());

            CreateMap<MerchantEmployee, EmployeeViewModel>()
                .ForMember(a => a.EmployeeId, p => p.MapFrom(s => s.MerchantEmployeeId))
                .ForMember(a => a.BranchId, p => p.MapFrom(s => s.MerchantBranchId))
                .ForMember(a => a.Branch, p => p.MapFrom(s => s.MerchantBranch))
                .ForMember(a => a.Profile, p => p.MapFrom(s => s.MerchantEmployeeProfile))
                .ForAllMembers(opt => opt.ExplicitExpansion());

            CreateMap<ChargeReference, ChargeReferenceViewModel>(MemberList.Destination)
                .ForMember(a => a.EmployeeId, p => p.MapFrom(s => s.MerchantEmployeeId))
                .ForMember(a => a.Employee, p => p.MapFrom(s => s.MerchantEmployee))
                .ForMember(a => a.ChargeReferenceId, p => p.MapFrom(s => s.ChargeReferenceId))
                .ForMember(a => a.BranchId, p => p.MapFrom(s => s.MerchantBranchId))
                .ForMember(a => a.Branch, p => p.MapFrom(s => s.MerchantBranch))
                .ForAllMembers(opt => opt.ExplicitExpansion());
```

Querying something like:

```
query{
  payments{
    paymentId
    chargeReference{
      chargeReferenceId
    }
  }
}
```

Raises this time the other well known error of:

```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field.",
      "locations": [
        {
          "line": 9,
          "column": 5
        }
      ],
      "path": [
        "payments",
        50,
        "chargeReference"
      ],
      "extensions": {
        "code": "HC0018"
      }
    }
  ]
}
```

Which of course is not valid.

The reason for this error is that the query this time is not translated properly as the query send to the database is:
```
  SELECT [p].[PaymentId]
      FROM [Payments].[Payment] AS [p]
      WHERE [p].[MerchantId] = @__SafeGetMerchantId_0

```

where I would expect something like:
```

  SELECT [p].[PaymentId],cr.chargeReferenceId
      FROM [Payments].[Payment] AS [p]
      INNER JOIN Payments.ChargeReference as cr on cr.ChargeReferenceId = p.ChargeReferenceId
      WHERE [p].[MerchantId] = @__SafeGetMerchantId_0
```

That is such a big issue for us, as we have created most of our platform's GQL API queries based on HotChocolate, EF and AutoMapper projections and small gql queries creates enormous sql statements.

**Comment by AntonC9018** [comment]
Not getting it to map nested entities at all. With configuration like this:
```cs
public class QueryType : ObjectType
{
    protected override void Configure(IObjectTypeDescriptor descriptor)
    {
        descriptor
            .Field("test")
            .Type<NonNullType<ListType<NonNullType<ObjectType<GraphQlPersonDto>>>>>()
            .UseDbContext<ApplicationDbContext>()
            // .UsePaging<NonNullType<ObjectType<GraphQlPersonDto>>>()
            .UseProjection()
            .UseFiltering()
            .UseSorting()
            .Resolve(ctx => ctx
                .DbContext<ApplicationDbContext>()
                .Set<Person>()
                .AsQueryable()
                .ProjectTo<Person, GraphQlPersonDto>(ctx));
    }
}
```
Entities and dtos like this:
```cs
public class GraphQlPersonDto
{
    public ID Id { get; set; }
    public string Name { get; set; }
    
    // Note: intentionally misspelt
    public List<GraphQlProjectDto> Projets { get; set; } = new();
}

public class GraphQlProjectDto
{
    public ID Id { get; set; }
    public string Name { get; set; }
}

public class Person
{
    public long Id { get; set; }
    public string Name { get; set; }
    public List<Project> Projects { get; set; } = new();
}

public class Project
{
    public long Id { get; set; }
    public long PersonId { get; set; }
    public Person Person { get; set; }
    public string ProjectName { get; set; }
}
```
And the mapping configuration like this:
```cs
        {
            CreateMap<GraphQlPersonDto, Person>(MemberList.Source)
                .ForMember(d => d.Projects, o => o.MapFrom(s => s.Projets))
                .ReverseMap()
                .ForAllMembers(opt => opt.ExplicitExpansion());
        }
        {
            CreateMap<GraphQlProjectDto, Project>(MemberList.Source)
                .ForMember(d => d.ProjectName, o => o.MapFrom(s => s.Name))
                .ReverseMap()
                .ForAllMembers(opt => opt.ExplicitExpansion());
        }
```
If I then do a query like such:
```graphql
query Test {
    test {
        name
        projets {
            id,
            name
        }
    }
}
```
I'm getting the following sql query generated:
```sql
 SELECT [p].[Name]
 FROM [People] AS [p]
```
And, obviously, no projects are returned.

It does return correct data on the client side if I omit explicit expansion, but then it fetches even those data that weren't requested. Like a query like this:
```graphql
query Test {
    test {
        name
        projets {
            id
        }
    }
}
```

Produces the following sql (it fetches the project name):
```sql
SELECT [p].[Id], [p].[Name], [p0].[Id], [p0].[ProjectName]
      FROM [People] AS [p]
      LEFT JOIN [Projects] AS [p0] ON [p].[Id] = [p0].[PersonId]
      ORDER BY [p].[Id]
```

**Comment by akolodkin** [comment]
I managed to find a solution for AutoMapper 11+ https://github.com/ChilliCream/graphql-platform/issues/4114#issuecomment-1518695940 provided by [BlackDice051](https://github.com/BlackDice051)

 Automapper map must have .ForAllMembers(x => x.ExplicitExpansion());  to make it work properly

```
public static class AutoMapperQueryableExtensions
{
    public static IQueryable<TDest> ProjectTo<TSource, TDest>(this IQueryable<TSource> query, IResolverContext context)
    {
        IMapper mapper = context.Service<IMapper>();

        context.LocalContextData =
            context.LocalContextData.SetItem(QueryableProjectionProvider.SkipProjectionKey,
                true);

        var visitorContext =
            new QueryableProjectionContext(
                context,
                context.ObjectType,
                context.Selection.Field.Type.UnwrapRuntimeType(), false);
        var visitor = new QueryableProjectionVisitor();
        visitor.Visit(visitorContext);

#pragma warning disable CS8631
        Expression<Func<TDest, object?>> projection = visitorContext.Project<TDest, object?>();
#pragma warning restore CS8631

        List<Expression<Func<TDest, object?>>> membersToExpand = new();

        VisitRoot(projection, membersToExpand);

        return query.ProjectTo(mapper.ConfigurationProvider, membersToExpand.ToArray());
    }
    
    private static void VisitRoot<TDest>(Expression<Func<TDest, object?>> root, List<Expression<Func<TDest, object?>>> expressions)
    {
        UnaryExpression lambdaBody = (UnaryExpression)root.Body;

        MemberInitExpression memberInit = (MemberInitExpression)lambdaBody.Operand;

        int level = 0;

        ParameterExpression parameter = MakeParameter(memberInit.Type, level);

        foreach (var expression in VisitMemberInit(memberInit, parameter, level))
        {
            var lambda = Expression.Lambda<Func<TDest, object?>>(expression, parameter);
            
            expressions.Add(lambda);
        }
    }

    private static IEnumerable<Expression> VisitMemberInit(MemberInitExpression memberInit,
        Expression path, int level)
    {
        var memberAssignments = memberInit.Bindings.Cast<MemberAssignment>();

        foreach (MemberAssignment memberAssignment in memberAssignments)
        {
            foreach (Expression expression in VisitMemberAssignment(memberAssignment, path, level))
            {
                yield return expression;
            }
        }
    }

    private static IEnumerable<Expression> VisitMemberAssignment(MemberAssignment memberAssignment, Expression path, int level)
    {
        var memberExpression = memberAssignment.Expression;

        var member = (PropertyInfo)memberAssignment.Member;

        if (memberExpression is MemberExpression)
        {
            yield return VisitPrimitive(member, path);
        }

        if (memberExpression is MemberInitExpression nestedMemberInit)
        {
            foreach (Expression expression in VisitNestedObject(nestedMemberInit, member, path, level))
            {
                yield return expression;
            }
        }

        if (memberExpression is MethodCallExpression toArrayCallExpr)
        {
            foreach (Expression expression in VisitNestedCollection(toArrayCallExpr, member, path, level))
            {
                yield return expression;
            }
        }
    }

    private static Expression VisitPrimitive(PropertyInfo member, Expression path)
    {
        Expression memberAccess = Expression.MakeMemberAccess(path, member);

        if (member is { PropertyType.IsValueType: true })
        {
            memberAccess = Expression.Convert(memberAccess, typeof(object));
        }

        return memberAccess;
    }

    private static IEnumerable<Expression> VisitNestedObject(MemberInitExpression nestedMemberInit, PropertyInfo member, Expression path, int level)
    {
        var nestedPath = Expression.MakeMemberAccess(path, member);

        foreach (Expression expression in VisitMemberInit(nestedMemberInit, nestedPath, level))
        {
            yield return expression;
        }
    }

    private static IEnumerable<Expression> VisitNestedCollection(MethodCallExpression toArrayCall, PropertyInfo member, Expression path, int level)
    {
        if (toArrayCall.Arguments[0] is not MethodCallExpression selectCall) 
            yield break;

        if (selectCall.Arguments[1] is not LambdaExpression selectLambda) 
            yield break;

        var nestedPath = Expression.MakeMemberAccess(path, member);

        var memberInit = (MemberInitExpression)selectLambda.Body;

        level++;

        ParameterExpression parameter = MakeParameter(memberInit.Type, level);

        var selectMethod = typeof(Enumerable)
            .GetMethods(BindingFlags.Static | BindingFlags.Public)
            .Single(mi => mi.Name == nameof(Enumerable.Select) &&
                          mi.GetParameters()[1].ParameterType.GetGenericArguments().Length == 2)
            .MakeGenericMethod(parameter.Type, typeof(object));

        foreach (var expression in VisitMemberInit(memberInit, parameter, level))
        {
            LambdaExpression lambda = Expression.Lambda(expression, parameter);

            yield return Expression.Call(null, selectMethod, nestedPath, lambda);
        }
    }

    private static ParameterExpression MakeParameter(Type type, int lambdaLevel)
    {
        return Expression.Parameter(type, "p_" + lambdaLevel);
    }
}
```

**Pull request merged**
