### PR TITLE
Opa Authorization Handler for AspNetCore

### PR DESCRIPTION
**Pull request by queil**
Implement authorization handler delegating authz to an OPA (Open Policy Agent) REST API endpoint. The handler should send a `POST` request to an OPA [Data API](https://www.openpolicyagent.org/docs/latest/rest-api/#data-api) endpoint.

### CODE REVIEW

**Comment by queil** [comment]
@PascalSenn I think I am ready for a review.

**Comment by michaelstaib** [comment]
Hey sorry for the wait ... we will do the review this week.

**Comment by michaelstaib** [comment]
I will do a bit of reformatting so that it fits with the code-style. Looks great so far.

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
I have merged it now into the V13 branch aka main. I will go over the interfaces before we do a final release. I think a couple could be internal .... I will ship the new package with preview 74

**Comment by michaelstaib** [comment]
Hey @queil in the test is a reference to a local server and all tests seem always to fail. Can you containerize this server? So we can package it with squadron for the tests?

**Comment by queil** [comment]
Sure, it should be trivial. I'll take a look shortly l.

**Comment by michaelstaib** [comment]
Awesome thank you

**Comment by queil** [comment]
OPA Server is already available as a Docker image. Does this work for you guys? https://hub.docker.com/r/openpolicyagent/opa/  Also, I'd probably should remove the embedded server from the tests though.

**Comment by michaelstaib** [comment]
Yes, lets package that up in squadron and then we can use the docker image in the tests.

**Comment by michaelstaib** [comment]
I will create an issue

**Pull request merged**
