### PR TITLE
Adding CONTRIBUTING and assets

### PR DESCRIPTION
**Pull request by joslat**
Added Contributing.md and related assets.

### CODE REVIEW

**Comment by steveoh** [comment]
I added a pr to your branch as well as some general comments. I think they may be helpful for saturday's meeting. https://github.com/joslat/hotchocolate/pull/1

**Comment by joslat** [comment]
Approved the suggestions and changes from @steveoh - Thanks Steve!

**Comment by michaelstaib** [comment]
Sorry was out the last two days. My main issue with this is that this is more like a personal experience report. I have looked at multiple OSS projects now and think that the best fit for us is really what the dotnet team did.

```
How can I contribute?

We welcome contributions! Many people all over the world have helped make this project better.
- Contributing explains what kinds of changes we welcome
- Workflow Instructions explains how to build and test
- Get Up and Running on .NET Core explains how to get nightly builds of the runtime and its libraries to test them in your own projects.
```

Each of the points links to a document explaining the process in an abstract way. Also they show the code style guide and things that are important.

https://github.com/dotnet/runtime/blob/master/CONTRIBUTING.md
https://github.com/dotnet/runtime/blob/master/docs/workflow/README.md
https://github.com/dotnet/runtime/blob/master/docs/project/dogfooding.md

CONTRIBUTING.md is pretty close to what we need. The other things like workflow and stuff have to be completely rewritten for our purposes since building this project and stuff is completely different. I do like the dos and donts. 

The `How can I contribute?` section should go in our new readme which like in the dotnet project points to the actual contribution guide.

What do you guys think? 

@joslat @rstaib @PascalSenn

**Comment by joslat** [comment]
mmm.. I like it and I can see the perfectionist spirit floating around, which is good. :)

There is a lot of information I do not fully know regarding different sections so I am unsure I can get this unless it is ok that everything in the CONTRIBUTING.md goes (changing project names et al).
Would this work?
Otherwise, @michaelstaib, @PascalSenn ... can we sync on it some minutes and I can get this file done? ;)

And, regarding the styleguide, should we copy it and later on, modify it? or somebody would like to take this head on?  @michaelstaib ?

On the Readme.md and dogfooding.md I love them, they are good to have but... if we change things they will need to be maintained... so maybe simplifying them would be good so to have time to be on the code part ... but just saying...

**Comment by rstaib** [comment]
@michaelstaib @PascalSenn I like those examples lets go with it.

**Comment by michaelstaib** [comment]
I am closing this one since we have no clear directions on this. Once we have we can reopen it again.

**Pull request closed without merging**
